### ISSUE TITLE
Vagrant 1.7.4 cannot parse: '1.3.0-alpha.3'. on Mac os

### ISSUE THREAD

**Issue by linearregression** [openshift/origin#10403]
[provide a description of the issue]
Box image name format fails vagrant 1.7.4 on MACOS
Vagrant 1.8.5 has an error of not able to ssh into the VM created, so now use 1.7.4
See log for 
"
Vagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z."
##### Version

[provide output of the `openshift version` or `oc version` command]
##### Steps To Reproduce
1. install vagrant 1.7.4
2.  vagrant init openshift/origin-all-in-one
3. VAGRANT_LOG=debug vagrant up &> debug.log
##### Expected Result

environment properly created and can be sshed into
##### Additional Information

Attached error log
opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in`block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in`block (2 levels) in run'
 INFO interface: error: A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
 INFO interface: Machine: error-exit ["Vagrant::Errors::BoxMetadataMalformedVersion", "A version of the box you're loading is formatted in a way that\nVagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version\nto be properly formatted. It should be in the format of\nX.Y.Z."]

**Comment by smarterclayton** [comment]
@thesteve0 have you hit this?

**Comment by thesteve0** [comment]
Yuppers - fixed in a new version of Vagrant. Don't get the latest version
though as that has a nasty SSH bug.

Thank you for reminding me that I need to rename the box and re-upload it
since this will probably affect all fedora users

**Comment by luigizuccarelli** [comment]
@thesteve0 Any update on this - still getting the 1.3.0-alpha.3 error - using fedora

**Comment by csayler** [comment]
still getting error for install-

vagrant 1.7.4 and virtualbox 5.0.4

attached error log:
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
 INFO interface: Machine: error-exit ["Vagrant::Errors::BoxMetadataMalformedVersion", "A version of the box you're loading is formatted in a way that\nVagrant cannot parse: '1.3.0-alpha.3'. Please reformat the version\nto be properly formatted. It should be in the format of\nX.Y.Z."]

**Comment by stevekuznetsov** [comment]
Nobody is running the pre-release builds for 1.3 anymore, surely.
