### ISSUE TITLE
Extended.idling and unidling unidling should work with TCP (when fully idled)

### ISSUE THREAD

**Issue by knobunc** [openshift/origin#10773]
```
------------------------------
idling and unidling unidling 
  should work with TCP (when fully idled) [Conformance]
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:309

STEP: Creating a kubernetes client
Sep  1 14:31:46.435: INFO: >>> kubeConfig: /tmp/openshift/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig

STEP: Building a namespace api object
Sep  1 14:31:46.479: INFO: configPath is now "/tmp/openshift/extended-test-cli-idling-r87sd-xpgny-user.kubeconfig"
Sep  1 14:31:46.479: INFO: The user is now "extended-test-cli-idling-r87sd-xpgny-user"
Sep  1 14:31:46.479: INFO: Creating project "extended-test-cli-idling-r87sd-xpgny"
STEP: Waiting for a default service account to be provisioned in namespace
STEP: Building a namespace api object
Sep  1 14:31:47.020: INFO: configPath is now "/tmp/openshift/extended-test-cli-idling-r87sd-cvgex-user.kubeconfig"
Sep  1 14:31:47.020: INFO: The user is now "extended-test-cli-idling-r87sd-cvgex-user"
Sep  1 14:31:47.020: INFO: Creating project "extended-test-cli-idling-r87sd-cvgex"
STEP: Waiting for a default service account to be provisioned in namespace
STEP: Creating the resources
Sep  1 14:31:47.389: INFO: Running 'oc create --namespace=extended-test-cli-idling-r87sd-cvgex --config=/tmp/openshift/extended-test-cli-idling-r87sd-cvgex-user.kubeconfig -f /data/src/github.com/openshift/origin/test/extended/testdata/idling-echo-server.yaml -o name'
STEP: Creating the idling file
STEP: Waiting for the endpoints to exist
STEP: Waiting for endpoints to be up
STEP: Idling the service
Sep  1 14:32:19.027: INFO: Running 'oc idle --namespace=extended-test-cli-idling-r87sd-cvgex --config=/tmp/openshift/extended-test-cli-idling-r87sd-cvgex-user.kubeconfig --resource-names-file /tmp/openshift/openshift-extended-tests/idling-services-246870143'
STEP: Waiting for the pods to have terminated
STEP: Connecting to the service IP and checking the echo
STEP: Collecting resource usage data
Sep  1 14:32:36.302: INFO: Closed stop channel. Waiting for 1 workers
Sep  1 14:32:36.302: INFO: Closing worker for 172.18.0.100
Sep  1 14:32:36.302: INFO: Waitgroup finished.
Sep  1 14:32:36.302: INFO: Unknown output type: . Skipping.
Sep  1 14:32:36.302: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "extended-test-cli-idling-r87sd-xpgny" for this suite.
STEP: Destroying namespace "extended-test-cli-idling-r87sd-cvgex" for this suite.
STEP: Cleaning up the idling file


• Failure [74.984 seconds]
idling and unidling
/data/src/github.com/openshift/origin/test/extended/idling/idling.go:466
  unidling
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:465
    should work with TCP (when fully idled) [Conformance] [It]
    /data/src/github.com/openshift/origin/test/extended/idling/idling.go:309

    Expected error:
        <*errors.errorString | 0xc82101c1e0>: {
            s: "unable to read data from echo server for service idling-echo: read tcp 172.18.0.100:55154->172.30.12.10:8675: read: connection reset by peer",
        }
        unable to read data from echo server for service idling-echo: read tcp 172.18.0.100:55154->172.30.12.10:8675: read: connection reset by peer
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/idling/idling.go:297
------------------------------
```

As seen in:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/5823/consoleText

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/7012/consoleFull

**Comment by stevekuznetsov** [comment]
@DirectXMan12 What's the status of you looking into this? This is a very wide-spread flake in our queue right now.

**Comment by smarterclayton** [comment]
@knobuc can you find someone to look at this since 1.5 is closing and solly has changed to land?

**Comment by knobunc** [comment]
Latest error was:

```
STEP: Dumping a list of prepulled images on each node
Nov  4 05:33:21.431: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "extended-test-cli-idling-0tqsq-j2px3" for this suite.
Nov  4 05:33:26.476: INFO: namespace: extended-test-cli-idling-0tqsq-j2px3, resource: bindings, ignored listing per whitelist
STEP: Destroying namespace "extended-test-cli-idling-0tqsq-rxjya" for this suite.
Nov  4 05:34:16.662: INFO: namespace: extended-test-cli-idling-0tqsq-rxjya, resource: bindings, ignored listing per whitelist
[AfterEach] idling and unidling
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:250
STEP: Cleaning up the idling file


• Failure in Spec Setup (JustBeforeEach) [184.987 seconds]
idling and unidling
/data/src/github.com/openshift/origin/test/extended/idling/idling.go:466
  unidling [JustBeforeEach]
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:465
    should work with TCP (when fully idled) [Conformance]
    /data/src/github.com/openshift/origin/test/extended/idling/idling.go:309

    Expected error:
        <*errors.errorString | 0xc8200e5780>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred
```

So it doesn't even get the pods up in 1 minute...

**Comment by deads2k** [comment]
@ncdc You may have just found this one in your log.  Looks like https://github.com/openshift/origin/blob/master/pkg/unidling/controller/controller.go#L96 creates a fake List method, that when called will not return a valid resourceVersion for the reflector to use for its watch.

**Comment by ncdc** [comment]
I can confirm in at least 1 jenkins failure for this flake that you see the unidling controller eventually repeatedly fails to watch Events with this:

```
reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
```

Once that happens, unidling is busted...

**Comment by ncdc** [comment]
I have tried modifying the fake List function to return a resource version of "0" but that isn't helping. I'm still debugging this.

**Comment by liggitt** [comment]
flaked in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9883/

**Comment by stevekuznetsov** [comment]
I feel like we need to re-evaluate this test. It's been a constant source of flakes for four months. This should really not be acceptable.

**Comment by smarterclayton** [comment]
I'm fairly certain it's because of the p0, which is making any test that
creates pods and is sensitive to multi minute delays break.  It's not
acceptable for start times on relatively unloaded systems to be 2+ minutes
- I don't recall this test being bad before we started the slow spike
upwards.

Once that p0 is fixed I agree this is first on the scrutiny list

On Jan 6, 2017, at 9:56 PM, Steve Kuznetsov <notifications@github.com>
wrote:

I feel like we need to re-evaluate this test. It's been a constant source
of flakes for four months. This should really not be acceptable.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10773#issuecomment-271058085>,
or mute the thread

**Comment by knobunc** [comment]
I completely agree with @smarterclayton.  I've run the idling/unidling cycle continuously with multiple going at once and can't reproduce this locally.  It feels like the slow pod startups.  We could change it to have different timeouts, but that feels like a weak answer.

**Comment by stevekuznetsov** [comment]
>  We could change it to have different timeouts, but that feels like a weak answer.

Two goals here, both of which have merit --
 1. reduce friction for changes to get into Origin
 2. make Origin better

Bumping timeouts to reduce the instances of this flake addresses 1 and can be done independently to work on 2 that would fix the problem for good.

**Comment by knobunc** [comment]
@stevekuznetsov the problem is that the timeouts that we need to bump are the ones in the service proxy for how long to hold on to a connection.  Now, we can bump them, but it's not just a test change, and we increase the number of connections that we need to handle at a time, and increase the risk of running out of sockets userspace can use.

**Comment by stevekuznetsov** [comment]
> but it's not just a test change,

Understood. Let's not change them, then.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10474/

**Comment by knobunc** [comment]
This is potentially resolved by https://github.com/openshift/origin/issues/10773

**Comment by bparees** [comment]
@knobunc did you mean to reference a different issue/PR?  this issue *is* 10773...

**Comment by stevekuznetsov** [comment]
If it's potentially resolved let's close it when we don't see it for a while

**Comment by knobunc** [comment]
Sorry, mis-paste.  It is potentially resolved by  #12754

**Comment by knobunc** [comment]
@stevekuznetsov that PR ups the timeout for the unidler, so it now holds the connections for 120s.  So that should give the pods plenty of time to start up.  If that is the real cause, then it is solved by that (although we may need to tweak the 60s in the tests to allow them to deal with the slower pod startup times we see in testing sometimes)

**Comment by bparees** [comment]
Still happening:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/293/

**Comment by DirectXMan12** [comment]
Problem extracted from test run logs (I've filtered so that only the relevant parts of the logs are shown):

```
I0217 10:23:39.229761   13020 unidlersocket.go:263] unidling TCP proxy start/reset for service extended-test-cli-idling-nbt2c-176g8/idling-echo:tcp-echo
I0217 10:23:39.288478   13020 unidlersocket.go:355] unidling proxy UDP proxy waiting for data for service extended-test-cli-idling-nbt2c-176g8/idling-echo:udp-echo
I0217 10:23:43.706987   13020 unidlersocket.go:221] unidling TCP proxy sent unidle event to wake up service extended-test-cli-idling-nbt2c-176g8/idling-echo:tcp-echo
I0217 10:23:43.707011   13020 unidlersocket.go:237] unidling TCP proxy has accumulated 1 connections while waiting for service extended-test-cli-idling-nbt2c-176g8/idling-echo:tcp-echo to unidle
I0217 10:23:43.770763   13020 controller.go:341] Scaled up DeploymentConfig "idling-echo" while unidling service extended-test-cli-idling-nbt2c-176g8/idling-echo
I0217 10:23:43.812998   13020 controller.go:249] Unable to fully process unidling request for extended-test-cli-idling-nbt2c-176g8/idling-echo (at 2017-02-17 10:23:43.70699947 -0500 EST), will retry: unable to update/remove idle annotations from extended-test-cli-idling-nbt2c-176g8/idling-echo: Operation cannot be fulfilled on endpoints "idling-echo": the object has been modified; please apply your changes to the latest version and try again
```

@knobunc We're failing up remove the annotations from the endpoints object since they've been updated in the mean time.

There are two problems here:

1. For the test: in the test, we see that the endpoints are up and expect things to have worked correctly the first time (even though in the real case we're fine just trying again later).

2. For the real-world case: in the retry logic, we'll never fully remove the annotations, because we skip removing the annotation from the set if we don't actually perform the scaling ourselves (i.e. not-yet-idle or already-unidled targets won't get removed).  This means if we succeed in scaling but fail in updating the endpoints, the annotations will never get removed.  @knobunc I don't remember if there was a reason we did this, or if it was an oversight.

**Comment by derekwaynecarr** [comment]
moving to p2, this should still be fixed but is not a blocker and could go in a patch release if required.

**Comment by DirectXMan12** [comment]
To summarize a discussion with @knobunc:

I think the solution here is to simply record the last idling-related scale time when we do the scale on the scalable (we already remove some annotations in the same operation where we change the scale, so this should be fine).  Then, we actually delete the scalable from the endpoint annotation, even if it's already unidled, but only if the last idling scale is from *after* the event that we're currently processing.
We specifically skip removing the item normally to handle the case where someone is still idling.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/427/

**Comment by stevekuznetsov** [comment]
Not blocking any release if we make it P1 now.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/1832/consoleFull#-163316032756cbb9a5e4b02b88ae8c2f77

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin/639/testReport/junit/(root)/Extended/idling_and_unidling_unidling_should_work_with_TCP__when_fully_idled___Conformance___local_/

New symptom.  Can we actually try and fix this.  The number of times it has failed are ridiculous

**Comment by soltysh** [comment]
Another one https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/901/consoleFull

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/1590/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3104/

**Comment by stevekuznetsov** [comment]
@knobunc @DirectXMan12 @derekwaynecarr looks like a suggest for this was discussed in March above: https://github.com/openshift/origin/issues/10773#issuecomment-284824012

What is the status on this? I know other underlying issues are bubbling up as failures for this test but this has been by far the most flaky test we have ever had in our suites and I would really love to see it get nailed down for good.

**Comment by stevekuznetsov** [comment]
Kind of amazing this stopped flaking out.

/close

**Comment by bparees** [comment]
> Kind of amazing this stopped flaking out.

sssshhh..you'll wake the beast.
