### ISSUE TITLE
cAdvisor does not return CPU metrics for 1.4

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#11199]
cAdvisor is returning empty cpu usage for origin 1.4 (built from master, commit ffdeb1bb546339f62722f507e1a12bdb9701c4c2)

```
  "stats": [
   {
    "timestamp": "2016-10-03T15:53:03.359772024-04:00",
    "cpu": {
     "usage": {
      "total": 0,
      "user": 0,
      "system": 0
     },

```
##### Version

commit ffdeb1bb546339f62722f507e1a12bdb9701c4c2

but I suspect this also affect the v1.4.0-alpha.0

In the v1.3.0 versions, cpu metrics are collected
##### Steps To Reproduce
1. build origin from git master
2. access the cAdvisor endpoint for container and verify that it has a zero value for cpu.

eg: 
curl -k -H "Authorization: Bearer `oc whoami -t`" -X POST -d '{"num_stats":1}' https://127.0.0.1:10250/stats/${PROJECT_NAME}/${POD_NAME}/${POD_ID}/${CONTAINER_NAME}

Alternatively, install origin metrics (https://docs.openshift.org/latest/install_config/cluster_metrics.html) and verify that the cpu graphs are empty.
##### Current Result

cpu metrics are all zero
##### Expected Result

cpu metrics to not be zero

**Comment by mwringe** [comment]
@spadgett the root cause is cAdvisor in the 1.4 version of OpenShift returing 0 values for the cpu usage

**Comment by mwringe** [comment]
@derekwaynecarr any idea here? This breaks the console graphing of cpu usage in 1.4

**Comment by derekwaynecarr** [comment]
1. Is openshift running as a container?
1. What version of docker?
1. What systemd version (i.e. systemctl --version)

If openshift is running as a container, this will not work until the following is merged upstream and we cherry-pick it into origin 1.4:
https://github.com/kubernetes/kubernetes/pull/33806

**Comment by mwringe** [comment]
docker version: 1.10.3
os: Fedora 24
systemd: 229

OpenShift is running directly on the machine, not in a docker container.

I know that cAdvisor doesn't necessarily work well with a newer systemd, was hoping that would have been resolved by now

**Comment by derekwaynecarr** [comment]
systemd 229 changed the cgroup hierarchy and put pid 1 in init.scope.
this caused a bug in runc using cgroup driver for systemd.
this bug is fixed in projectatomic/docker-1.12 but it has not yet been published for rpm install on F24.

**Comment by mwringe** [comment]
I am now running the fedora docker 1.12 rpms which should have this fix, and yet I still don't see any difference here with the cpu usage, its still zero

**Comment by derekwaynecarr** [comment]
@sjenning -- ptal

**Comment by sjenning** [comment]
i've been able to recreate. debugging now.

**Comment by sjenning** [comment]
could be related to this https://github.com/openshift/origin/commit/960774831eef8ac426e793106f21a5765f55a246

**Comment by sjenning** [comment]
yes, reverting https://github.com/openshift/origin/commit/960774831eef8ac426e793106f21a5765f55a246 fixes the issue

**Comment by sjenning** [comment]
Ok gathering information:

opencontainers/runc PR that allows for all cgroup mount points:
https://github.com/opencontainers/runc/pull/1049

PR that vendors this into cAdvisor:
https://github.com/google/cadvisor/pull/1476

This isn't vendored into any version of projectatomic/docker right now.

Hack commit to get cAdvisor working on RHEL for openshift/origin:
https://github.com/openshift/origin/commit/960774831eef8ac426e793106f21a5765f55a246

IIUC, the fix for this issue is to vendor the fixed cAdvisor into origin and revert the hack commit.

**Comment by smarterclayton** [comment]
Yes

**Comment by sjenning** [comment]
Just out of morbid curiosity, I wanted to find out why cpuacct,cpu is inverted for RHEL7.  Turns out that the list of cgroup subsystems is a statically defined enum in the kernel:
https://github.com/torvalds/linux/blob/master/include/linux/cgroup_subsys.h.

For v3.10 (RHEL7) that subsystem list is converted into a linked list which inserts at the head, inverting the list.

In v3.14, the support for adding cgroup subsystems as modules was dropped and the code was greatly simplified, removing the need for the linked list and reversing the order for users of ```for_each_subsys```

https://github.com/torvalds/linux/commit/3ed80a62b

Upstream ```for_each_subsys```
https://github.com/torvalds/linux/blob/master/kernel/cgroup.c#L557

v3.10 ```for_each_subsys```
https://github.com/torvalds/linux/blob/v3.10/kernel/cgroup.c#L268

```proc_cgroup_show``` uses ```for_each_subsys``` to create the output for /proc/<pid>/cgroup

So... mystery solved!

**Comment by smarterclayton** [comment]
Gets out knife.  Stabs self.  Chooses another profession.

**Comment by derekwaynecarr** [comment]
Linked lists should only support append!

**Comment by sjenning** [comment]
This is fixed by https://github.com/openshift/origin/pull/11642

**Comment by mwringe** [comment]
Bugzilla opened for this: https://bugzilla.redhat.com/show_bug.cgi?id=1390502

**Comment by ncdc** [comment]
#11642 was superseded by #11709 which has merged, so this can be closed now
