### ISSUE TITLE
Registry: after 'atomic install atomic-registry-install' atomic-registry-master has failed message

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#11490]
After 'atomic install atomic-registry-install' atomic-registry-master has failed message

```
Oct 21 14:12:29 katello.example.com atomic-registry-master[19649]: I1021 18:12:29.937888       1 scheduler.go:100] Failed to schedule pod: default/docker-registry-1-deploy
```

I was told this was harmless but is disconcerting to see that in the journalctl constantly repeating every 10 seconds or so.
##### Version

docker.io/projectatomic/atomic-registry-install:latest
##### Steps To Reproduce
1. atomic install docker.io/projectatomic/atomic-registry-install:latest
2. journalctl -fu atomic-registry-master
##### Current Result

Failed message every 10 seconds or so
##### Expected Result

No failed messages

**Comment by aweiteka** [comment]
@thomasmckay this should have been resolved by #11470 and #10706. Can you confirm?

**Comment by thomasmckay** [comment]
@aweiteka I still see this on a fresh install from docker.io

**Comment by Syffs** [comment]
+1

**Comment by aweiteka** [comment]
Old issue. Unable to reproduce. Please re-open if necessary.
