### ISSUE TITLE
oadm top images -n <namespace> list the all the images in different namespaces

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#12253]
[provide a description of the issue]
oadm top images -n <namespace> list the all the images in different namespaces, as a customer, I want to list the  images that belongs to the explicit namespace, 
##### Version
[provide output of the `openshift version` or `oc version` command]
openshift v1.5.0-alpha.0+595b6bd-376
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
##### Steps To Reproduce
1. [step 1]
Launch a openshift cluster, and create imagestream under the openshift project, then create a build using:
oc new-project haowang1
oc new-build https://github.com/openshift/ruby-ex
2. [step 2]
After the build complete, check the images under the haowang project
oadm top images -n haowang1
##### Current Result
NAME                                                                    IMAGESTREAMTAG                  PARENTS                 USAGE   METADATA        STORAGE
sha256:79ad4b35f8764f487ae84ee63ea06b301eb10b2d8999f91557419dc5d75b0698 <none>                          <none>                  <none>  yes             216.10MiB
sha256:5827c32e10233f75fb26d82f37bd1a3ad460f06079c7a71a76b795afef22dcf1 <none>                          <none>                  <none>  yes             198.97MiB
sha256:d7286c065860f7f67f22056a9d3cdb79784c4dfc0d79f6721921f5c22e840e47 <none>                          <none>                  <none>  yes             44.82MiB
sha256:1e35519c1f7f964b1da4852ab61a8aa42f8b1d617748b46d06b7f938e9ecd3f5 <none>                          <none>                  <none>  yes             23.83MiB
sha256:9f8cfef74cefab63036ae16cac8766e76c0610a0c560fab83e093da740aa4369 <none>                          <none>                  <none>  yes             150.73MiB
sha256:be4ca36e26387d1ae0c00f14a6e6e56d5276db38cf97da9e27887f081e39c5b6 <none>                          sha256:1e35519c1f...    <none>  yes             158.87MiB
sha256:e2018445830cac5de99b3a41da007906fc607ca1e98336579536b8d1fb59019e <none>                          <none>                  <none>  yes             44.39MiB
sha256:4143584de718ef477fe03e3ae15985c68e0ce9dca8ba089dfa5927e800e59e69 <none>                          <none>                  <none>  yes             123.13MiB
sha256:9161c262d34a302b92354b517ea6a92c0c908394541c71abb8bfad85962100ac <none>                          <none>                  <none>  yes             67.78MiB
sha256:1a1cb72525f5b5c139e126e23ac5463e8b560ef19bd8032ee016805bc3a52272 <none>                          <none>                  <none>  yes             48.23MiB
sha256:94b4122f3a1ccc4fad51046ca410db555125a55b6b0ec4defd454f3a116c736f haowang1/ruby-ex (latest)       sha256:1e35519c1f...    <none>  yes             158.87MiB
sha256:8fb765c8210356f879f67fbf4d926f0291da5e44be838bea000f9847a27f6ad9 <none>                          <none>                  <none>  yes             57.91MiB
sha256:cab3aa8ae9ebf0ea7eb309c3a21f9d04c7c9a357e61ae241e377234398b4648c <none>                          <none>                  <none>  yes             40.20MiB
sha256:1e9fb5e7a80cac7b881282ea8c603f147b4112ea17b0b42f9d5da92301fc0af4 <none>                          <none>                  <none>  yes             72.08MiB
sha256:58d0593918b98ed5b4f33ae06e85b9131013b3808bb5dad7b18d5aa5244ed714 <none>                          <none>                  <none>  yes             27.18MiB
sha256:b398af5a4f9859ba08559529238565a22061aa7da009400aef0b64aea1ef1ce8 <none>                          sha256:1e35519c1f...    <none>  yes             158.87MiB
sha256:a0512aad09bd45688e39473ea8a4e3dae45e9077c6973aae04105d6c4dab0bf3 <none>                          <none>                  <none>  yes             27MiB
sha256:9429be9f0188443cfd7ee0607760beffe0aad3d43c78bdd6d1c5f87925918f7b <none>                          <none>                  <none>  yes             41.48MiB
sha256:b7e2224696b2edf558488bc96b2da855b5fa77f726e974fba2600af2c2e7162b <none>                          <none>                  <none>  yes             36.11MiB
sha256:65699ee49790c2def821299ca39ae10202e03d83ccfc3c2090f4d424b5b5deee <none>                          <none>                  <none>  yes             34.16MiB
sha256:cc6ecaa9491ba7859f79a1a453336ee056f473e88dd711d47226001447f8b018 <none>                          <none>                  <none>  yes             27.57MiB
sha256:c827903eff7c10706bae8208216e884955ec744e131a256823dd838da53a0fd2 <none>                          <none>                  <none>  yes             25.10MiB
sha256:3f81d222ef07a7ef8e0f2d936a2741053da87b8ff1527190d814eac51f77635e <none>                          <none>                  <none>  yes             152.87MiB
sha256:7fdfc09047439b9af110112fa3d289187af6a978addcb9d0e48b018c07728310 <none>                          <none>                  <none>  yes             19.17MiB
sha256:0984a4bd1809a7e63f471b907b7f60b40dbb770c6b4a790281288f490fd9d30e <none>                          <none>                  <none>  yes             13.94MiB
sha256:2d8181cfd1934082672c17a9f0056598fc6416cdba5a3e2c210d97ec8a6ad234 <none>                          <none>                  <none>  yes             126.96MiB
sha256:9cfa0ccfa3560cee94959508f250ad12edddea15ecc2422b9687bf6d645d8d21 <none>                          <none>                  <none>  yes             41.54MiB

##### Expected Result
We should only list the images that belongs to the namespace haowang1

**Comment by wanghaoran1988** [comment]
And I find after I delete the project haowang1 which means the Imagestrem under this project is deleted, and the built out images is un referenced, and then run the oadm prune images --confirm, after that, when I run oadm top images , the images are still there, seems we didn't prune the metadata of the unused images.

**Comment by pweil-** [comment]
@soltysh this looks like it may really be 2 issues 

1. namespace flag not being honored
2. pruned images still showing

Please feel free to break it up

**Comment by soltysh** [comment]
Hmmm.... I've fixed no 1. somewhere already, so that's a small issue. But no 2, if that's true that means images were not pruned actually, pruning should completely remove them from etcd, iirc.

**Comment by wanghaoran1988** [comment]
@soltysh Blobs in the registry seems pruned according to the log, but the images info are still exists in the etcd, we can get them using cmd oc get images.

**Comment by wanghaoran1988** [comment]
Create a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1404898) for tracking the 2nd issue

**Comment by soltysh** [comment]
Cool thx, will look into both.

**Comment by soltysh** [comment]
For the part where we don't honor namespace flag, I just double checked and it's applied correctly. The thing is that images are not namespaced ever (unless actually pruned) that's why they're being shown even after removing the project. I've just run `oadm top images -n test` and although I still see all images, the part that informs about ImageStreams (which are namespaced resource) is gone for anything other then test. So the first part is working as expected. Looking into 2nd part of the issue.

**Comment by soltysh** [comment]
I've also verified the pruning problem - everything is being pruned as expected. I think the reason you didn't have the image removed was the default value of `--keep-younger-than` flag which is one hour. As soon as I set this so that the newly built image falls into it it was removed, in my case `oadm prune images --keep-younger-than=1m --loglevel=1 --confirm` worked as expected. Having said all that I'm closing this issue as already fixed.
