### ISSUE TITLE
extended test flake: Services basic functionality should allow connections to another pod

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12625]
Test times out (10s) waiting for wget, probably because SDN has trailed behind in applying networking updates.  We should *probably* bump the timeout on wget to something longer.  10s is really long, of course, so it could be a more serious problem in networking.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/3368/testReport/junit/(root)/Extended/_networking__services_basic_functionality_should_allow_connections_to_another_pod_on_a_different_node_via_a_service_IP/

```
/data/src/github.com/openshift/origin/test/extended/networking/services.go:20
Expected success, but got an error:
    <*errors.errorString | 0xc82149cbe0>: {
        s: "pod 'service-wget' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:2017-01-23 12:58:05 -0500 EST FinishedAt:2017-01-23 12:58:08 -0500 EST ContainerID:docker://705777249aab8a54745373e401abc2535235e84a55a0a42317d50b5123406a11}",
    }
    pod 'service-wget' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:2017-01-23 12:58:05 -0500 EST FinishedAt:2017-01-23 12:58:08 -0500 EST ContainerID:docker://705777249aab8a54745373e401abc2535235e84a55a0a42317d50b5123406a11}
/data/src/github.com/openshift/origin/test/extended/networking/services.go:19
```

**Comment by smarterclayton** [comment]
@openshift/networking

**Comment by knobunc** [comment]
It timed out waiting 3m for pods to start.  @smarterclayton are we sure that https://github.com/openshift/origin/issues/11016 is resolved?  Or should I lengthen the wait time?

**Comment by smarterclayton** [comment]
11016 is not resolved.  I'm worried about much more than 3 min in general.

On Jan 23, 2017, at 3:23 PM, Ben Bennett <notifications@github.com> wrote:

It timed out waiting 3m for pods to start. @smarterclayton
<https://github.com/smarterclayton> are we sure that #11016
<https://github.com/openshift/origin/issues/11016> is resolved? Or should I
lengthen the wait time?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12625#issuecomment-274605835>,
or mute the thread

**Comment by knobunc** [comment]
Closing since increasing the wait time seems wrong.  This is a dupe of https://github.com/openshift/origin/issues/11016
