### ISSUE TITLE
Ansible task failure (permission denied)

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13606]
```
TASK [openshift_sanitize_inventory : Ensure a valid deployment type has been given.] ***
task path: /usr/share/ansible/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml:22
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Please set openshift_deployment_type to one of:\norigin, online, enterprise, atomic-enterprise, openshift-enterprise"
}
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'

PLAY RECAP *********************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=1   

++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: INSTALL ORIGIN ##########
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/735/consoleFull

**Comment by bparees** [comment]
here too:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/734/consoleFull

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/openshift/aos-cd-jobs/pull/166

**Comment by stevekuznetsov** [comment]
Changes are pushed, jobs are updated -- will keep this open for a bit in case people need to re-trigger jobs

**Comment by bparees** [comment]
looks like it's still failing:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/1140/consoleFull#12079938665849c75fe4b0052e114d805c

**Comment by stevekuznetsov** [comment]
@bparees that failure is #13739 . This issue (deployment type) is resolved.
