### ISSUE TITLE
error to "oc cluster up" with ocp version 3.5.5.5

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#13815]
````
oc cluster up --version v3.5 --image registry.access.redhat.com/openshift3/ose --public-hostname 127.0.0.1 --routing-suffix apps.127.0.0.1.nip.io --host-data-dir /Users/jmorales/.oc/profiles/3_5/data --host-config-dir /Users/jmorales/.oc/profiles/3_5/config --host-pv-dir /Users/jmorales/.oc/profiles/3_5/pv --use-existing-config -e TZ=CEST
Running in developer mode, using DOCKER_HOST=tcp://192.168.65.2:2375
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.5 ...
Pulling image registry.access.redhat.com/openshift3/ose:v3.5
Pulled 2/4 layers, 50% complete
Pulled 3/4 layers, 75% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.5 image ...
   Pulling image registry.access.redhat.com/openshift3/ose:v3.5
   Pulled 2/4 layers, 50% complete
   Pulled 3/4 layers, 75% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using public hostname IP 127.0.0.1 as the host IP
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
FAIL
   Error: could not update OpenShift configuration
   Caused By:
     Error: Invalid character(s) found in patch number "5.5"
````

![image](https://cloud.githubusercontent.com/assets/78350/25182269/5ba86dda-2514-11e7-9b30-72be3f53c3d0.png)

I works fine with oc (origin) client pre 3.6 (tested with 1.5.0-rc.0) as well as with OCP client (tested with 3.5.5.5)

##### Version
````
oc version
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
features: Basic-Auth
````

**Comment by bparees** [comment]
this worked fine for me. (I used a current master origin oc binary) please reopen if it's still an issue for you.

```
$ oc cluster up --version v3.5 --image registry.access.redhat.com/openshift3/ose --public-hostname 127.0.0.1 --routing-suffix apps.127.0.0.1.nip.io --host-data-dir /Users/jmorales/.oc/profiles/3_5/data --host-config-dir /Users/jmorales/.oc/profiles/3_5/config --host-pv-dir /Users/jmorales/.oc/profiles/3_5/pv --use-existing-config -e TZ=CEST
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.5 ...
Pulling image registry.access.redhat.com/openshift3/ose:v3.5
Pulled 2/4 layers, 50% complete
Pulled 2/4 layers, 50% complete
Pulled 2/4 layers, 50% complete
Pulled 2/4 layers, 50% complete
Pulled 3/4 layers, 75% complete
Pulled 3/4 layers, 75% complete
Pulled 3/4 layers, 75% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://127.0.0.1:8443

You are logged in as:
    User:     developer

To login as administrator:
    oc login -u system:admin
```

**Comment by csrwng** [comment]
This has been fixed recently in origin master (before we were not able to parse the entire version string)

**Comment by detiber** [comment]
This issue is still present for multi-arch 3.6 build atomic-openshift-clients-3.6.172.0.4-1.git.0.8ad1540.el7arches.ppc64le

**Comment by bparees** [comment]
@csrwng so this is fixed in origin master and ocp 3.6, but still needs backporting to OCP 3.5 and earlier, right?  (apparently 3.5 and earlier just moved to 5 digit versions too)

**Comment by csrwng** [comment]
@bparees yes

**Comment by bparees** [comment]
ok i'll work on those.

**Comment by bparees** [comment]
This is not caused by the same openshift version parsing logic that broke in 3.6.  3.5 and earlier did not do anything w/ the openshift server version.  What is failing here is something else related to patching the master-config, i haven't gotten to the bottom of it yet.

**Comment by bparees** [comment]
ok so this was determined to be because @jorgemoralespou was using a 3.6 oc binary(or what was effectively 3.6 at the time - master).  We've fixed the version parsing in the 3.6 binary.  The 3.5 and earlier binaries did not do any version parsing, so they should continue to work fine (no backport needed).

@jorgemoralespou can you confirm the version of the oc binary you were using when you hit this?

@jupierce fyi. if correct, there will not need to be any backport to 3.5/3.4/etc for cluster up to tolerate the new 5 digit versions.

**Comment by jorgemoralespou** [comment]
@bparees, version is in the report. Can't validate anything more as I'm on PTO without my laptop.

**Comment by bparees** [comment]
Thanks, So yes it was a 3.6 build.

**Comment by maci0** [comment]
Issue still persists

```
[maci@x1c ~]$ oc cluster up --image='registry.access.redhat.com/openshift3/ose' --image-streams=rhel7  --version='v3.6'
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.6 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.6 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
FAIL
   Error: could not update OpenShift configuration
   Caused By:
     Error: Invalid character(s) found in patch number "173.5"
[maci@x1c ~]$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
[maci@x1c ~]$ 
```

**Comment by bparees** [comment]
unfortunately the fix was not included in the origin 3.6.0 release, it was delivered after.

**Comment by maci0** [comment]
ok, built latest master and it works.
I hope this will make it into a minor release.
