### ISSUE TITLE
Prometheus Master Template seems to not be working on Openshift

### ISSUE THREAD

**Issue by gbaufake** [openshift/origin#14783]
Master Template (@smarterclayton commit 306e23f721647b3dc662e0c662b706ad8901937d ) seems not to be working for me.

##### Version
`oc v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
features: Basic-Auth`

`openshift v3.5.0.55
kubernetes v1.5.2+43a9be4`

##### Steps To Reproduce
1. `oc new-app -f origin/examples/prometheus/prometheus.yaml` from master

##### Current Result

> Deploying template "prometheus/prometheus" for "origin/examples/prometheus/prometheus.yaml" to project prometheus 
> Prometheus
> A monitoring solution for an OpenShift cluster - collect and gather metrics from nodes, services, and the infrastructure.`
> . With parameters:
        * NAMESPACE=kube-system
        * IMAGE_PROXY=registry.svc.ci.openshift.org/ci/oauth-proxy:latest
        * IMAGE_PROMETHEUS=registry.svc.ci.openshift.org/ci/prometheus:latest
        * SESSION_SECRET=uoYJ1rUJ2fKv2c0Rqr4tKmsuATUpmRbpAVA7uUgdt51 # generated`
> --> Creating resources ...
    error: serviceaccounts "prometheus" already exists
    error: clusterrolebinding "prometheus-cluster-reader" already exists
    error: Route "prometheus" is invalid: spec.tls.destinationCACertificate: Required value
    error: services "prometheus" already exists
    error: secrets "prometheus-proxy" already exists
    error: deployments.extensions "prometheus" already exists
    error: configmaps "prometheus" already exists
--> Failed

##### Expected Result

- Prometheus installed on Openshift Project

**Comment by juliusv** [comment]
@smarterclayton I also just ran into this (`spec.tls.destinationCACertificate: Required value`) with:

OpenShift Master: v1.5.1+7b451fc
Kubernetes Master: v1.5.2+43a9be4

(as installed by `oc cluster up` with `oc` 1.5.1 from the GitHub releases)

The error is only for the route, so it still tries to deploy Prometheus (though that seems to fail for other reasons for me now - the oauth proxy isn't getting its service account token and oauth secret mounted in and crashing).

**Comment by smarterclayton** [comment]
Yeah, right now the template is only supported on master "oc" and the
"latest" images while we get everything ready to run.

**Comment by mfojtik** [comment]
@smarterclayton hups, I fixed the template to work on older masters (by using legacy v1 api for resources...)

**Comment by gbaufake** [comment]
@mfojtik Still having issues with
`--> Creating resources ...
    error: serviceaccounts "prometheus" already exists
    error: clusterrolebinding "prometheus-cluster-reader" already exists
    error: Route "prometheus" is invalid: spec.tls.destinationCACertificate: Required value
    error: services "prometheus" already exists
    error: secrets "prometheus-proxy" already exists
    error: deployments.extensions "prometheus" already exists
    error: configmaps "prometheus" already exists
--> Failed`

**Comment by mfojtik** [comment]
@gbaufake @pweil- @smarterclayton said that the prometheus template is for 3.6+ clusters only. Maybe we just need to update readme to state that.

**Comment by gbaufake** [comment]
@mfojtik 
Yes, I think update readme for 1.6 or 3.6 will be good for now.
