### ISSUE TITLE
openshift-master leaks memory

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1530]
I have observed over the span of several weeks of different builds that if I leave openshift-master running for a few days (doing nothing in particular), it will consume at least a GB of RAM by itself. Not sure it's just the master, nodes may be as bad, but I just thought I'd open this. I'm not sure the best way to debug this, any pointers to information I should gather would be helpful.

**Comment by smarterclayton** [comment]
Run with OPENSHIFT_PROFILE=web set, you can then trigger a heap dump via http://127.0.0.1/debug/pprof

**Comment by sosiouxme** [comment]
More specifically, http://127.0.0.1:6060/debug/pprof/heap?debug=1

**Comment by sosiouxme** [comment]
@smarterclayton or whoever... I did above heap dump, ran it through pprof web, and came out with this.
![heap](https://cloud.githubusercontent.com/assets/29690/7073033/a09ae6aa-debe-11e4-8594-3e9e9d03fb06.png)

I'm... not quite sure how to read that. I'm not sure if "heap" dumps current state of heap, or profiles heap allocations (I think the latter). Seems like tls and json are burning a lot of RAM, but are they then releasing it or not?

**Comment by sosiouxme** [comment]
Trying the attachment again.
![heap](https://cloud.githubusercontent.com/assets/29690/7073130/4d73e07a-debf-11e4-9ac1-2517dedd80d8.png)

**Comment by sosiouxme** [comment]
Trying the attachment again.
![heap](https://cloud.githubusercontent.com/assets/29690/7073169/82fa2100-debf-11e4-92e0-d1df84cac14a.png)

**Comment by sosiouxme** [comment]
Apparently github just hates me.

**Comment by sosiouxme** [comment]
Trying the attachment again.
[heap](https://cloud.githubusercontent.com/assets/29690/7073843/2f15ed12-dec4-11e4-8ec9-7bbf8b59f0c0.png)

**Comment by smarterclayton** [comment]
I think someone is forgetting a request body.Close()

**Comment by sosiouxme** [comment]
I'm pretty sure this is resolved now.

**Comment by TomasTomecek** [comment]
IMO this still happens in 0.4.3. After one day of running master, memory consumption went from 8% to 70% (VM, 2GB ram).

**Comment by smarterclayton** [comment]
We haven't picked up this change from upstream yet.

**Comment by TomasTomecek** [comment]
Aha, that explains a lot. Would be great if you could write a comment here once it's released.

**Comment by TomasTomecek** [comment]
@smarterclayton is this in 0.4.4? So I can verify

**Comment by smarterclayton** [comment]
It's not, our next rebase will probably be next week.

**Comment by mmilata** [comment]
I have tried to find out if this is fixed in master (0189d1e) and found that 0.4.4 looks good while the git version leaks somewhat:

![os044](https://cloud.githubusercontent.com/assets/85857/7654754/a3dc04b6-fb1f-11e4-8951-4bc98bbc83be.png)
![osgit](https://cloud.githubusercontent.com/assets/85857/7654758/a9c1a796-fb1f-11e4-9fb3-e5fad7488158.png)

These are two identical VMs with 1G RAM. The 0.4.4 uses all-in-one setup while the git version uses master and node, both have loglevel=2. I created two builds on each after starting the service and then let it idle overnight (similar load under which we've observed the leaks). Not sure what angered the node today @ 13:00.

What can I do to help fix this?

**Comment by smarterclayton** [comment]
You'd need to trigger a heap profile.  Turn on OPENSHIFT_PROFILE=web, then from http://localhost:6060/debug/pprof you can trigger a heap profile.  Do it over an hour interval and then send both to me.

**Comment by mmilata** [comment]
@smarterclayton here they are: https://mmilata.fedorapeople.org/openshift/openshift-cc9bdf8-pprof-heap1 https://mmilata.fedorapeople.org/openshift/openshift-cc9bdf8-pprof-heap2

**Comment by smarterclayton** [comment]
I don't see anything excessive here.  Can you let the master run and get a heap dump later?  The info you have doesn't have an excessive amount of held references for anything I can detect.

----- Original Message -----

**Comment by mmilata** [comment]
@smarterclayton here's couple more hours of idling: https://mmilata.fedorapeople.org/openshift/openshift-cc9bdf8-pprof-heap3.xz (forgot to not suspend my computer over weekend:()

Please let me know if you want another profile later or if I can delete the VM.
