### ISSUE TITLE
cannot log into registry

### ISSUE THREAD

**Issue by mibaboo** [openshift/origin#16332]
Hi

I have setup origin using ansible advanced installation. The internal registry has been deploy successfully however I cannot log into, from the command line and web console. When I try from my browser https://hostname:8443/svc/registry-console I am not prompted for a user and password. I get the following message.

> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "User \"system:anonymous\" cannot \"get\" on \"/svc/registry-console\"",
>   "reason": "Forbidden",
>   "details": {},
>   "code": 403
> }

From the command line 
`docker login -u $(oc whoami) -p $(oc whoami -t ) hostname:8443
`
I get this message

> Error response from daemon: Login: Account is not active. Please see the documentation of the registry https://hostname:8443/v1/ for instructions how to activate it.

##### Version
[provide output of the `openshift version` or `oc version` command]

openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://hostname:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

**Comment by bparees** [comment]
what does "hostname" represent?  is that the route for your registry service?

**Comment by csrwng** [comment]
@mibaboo you may be confusing the registry console with the registry service endpoint which are different things.

From inside the cluster, you can login to the registry using the registry service ip
(https://docs.openshift.org/latest/install_config/registry/accessing_registry.html#access-logging-in-to-the-registry)

If you want to login to the registry from outside the cluster, you need to expose the registry using a route first.
(https://docs.openshift.org/latest/install_config/registry/securing_and_exposing_registry.html#exposing-the-registry)

**Comment by mibaboo** [comment]
@bparees the hostname represents the server it running on

**Comment by mibaboo** [comment]
@csrwng 
From **inside the cluster** I got the internal ip using `oc get all`

> NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
> svc/docker-registry    172.30.156.148   <none>        5000/TCP                  7d
> svc/kubernetes         172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     7d
> svc/registry-console   172.30.232.96    <none>        9000/TCP                  7d
> svc/router             172.30.161.169   <none>        80/TCP,443/TCP,1936/TCP   7d

`docker login -u $(oc whoami) -p $(oc whoami -t ) 172.30.156.148:5000`

Error 

> response from daemon: Get https://172.30.156.148:5000/v1/users/: x509: cannot validate certificate for 172.30.156.148 because it doesn't contain any IP SANs


**outside the cluster**
Since I set this up using the ansible playbook, it created the passthrough. See output of `oc status`

https://docker-registry-default.router.default.svc.cluster.local **(passthrough) (svc/docker-registry)**
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v3.6.0 
    deployment #2 deployed 3 days ago - 0 pods
    deployment #1 failed 7 days ago: cancelled by the user

svc/kubernetes - 172.30.0.1 ports 443->8443, 53->8053, 53->8053

https://registry-console-default.router.default.svc.cluster.local **(passthrough) (svc/registry-console)**
  dc/registry-console deploys docker.io/cockpit/kubernetes:latest 
    deployment #2 deployed 2 days ago - 1 pod
    deployment #1 failed 7 days ago: config change

**Comment by bparees** [comment]
@mibaboo pretty sure among other things you need to add 172.30.0.0/16 as an insecure docker registry for your daemon.  That should fix the docker login bit, as long as you're doing this from a machine that has access to the cluster network (internal ips).

for the browser side, you need to go `https://registry-console-default.router.default.svc.cluster.local`  (not port 8443, not /svc/registry-console).

**Comment by mibaboo** [comment]
@bparees 
I have added the insecure registry for my daemon. However I still cannot login.

`docker login -u $(oc whoami) -p $(oc whoami -t ) 172.30.156.148:5000
`
Error

> A communication error occurred: "Connection refused"

**Comment by bparees** [comment]
what machine are you running docker login on?  It needs to be a machine that has access to the internal cluster network, since you're trying to access the registry by its internal service ip.

**Comment by mibaboo** [comment]
@bparees ok I assumed the registry runs on the master, apologies :) 

I have logged in from the command line successfully.

Now how do I login from the browser?  the passthrough svc/docker-registry "connection refused"
I have update my hosts file but when I hit  https://registry-console-default.router.default.svc.cluster.local  I still get connect refused.

**Comment by bparees** [comment]
@mibaboo is your host entry pointing to svc/docker-registry or svc/docker-console?  You need your host entry to point registry-console-default.router.default.svc.cluster.local to the ip address of the registry-console(not docker-registry) service.

**Comment by mibaboo** [comment]
@bparees the hosts files is pointing to the console. You can close this ticket. There are to many issues to address in one ticker. I will log anther if needed. Thank you
