### ISSUE TITLE
Forbidden: this image is prohibited by policy: only images imported into the registry are allowed (openshift/origin-deployer:v3.6.0)

### ISSUE THREAD

**Issue by e-minguez** [openshift/origin#16749]
Trying to deploy an image from an external registry fails with the $subject error.

##### Version
```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://origin-ait.example.com:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Modify master-config.yaml with the following snippets:
```
admissionConfig:
  pluginConfig:
    ...
    openshift.io/ImagePolicy:
      configuration:
        kind: ImagePolicyConfig
        apiVersion: v1
        executionRules:
        - name: execution-denied
          matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
        - name: allow-images-from-dockerhub
          onResources:
          - resource: pods
          - resource: builds
          matchRegistries:
          - docker.io
          - myregistry.example.com
          - registry.access.redhat.com
          - 172.30.79.144
...
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: docker.io
  - domainName: '*.docker.io'
  - domainName: '*.redhat.com'
  - domainName: '*.example.com'
  disableScheduledImport: false
...
```
2. Restart masters services (both API and controllers)
3. IS created as:
```
$ oc get is nodejs-mongo-persistent -o yaml
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes in the application image
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ImageStream","metadata":{"annotations":{"description":"Keeps track of changes in the application image","openshift.io/image.insecureRepository":"true"},"labels":{"template":"nodejs-mongo-persistent"},"name":"nodejs-mongo-persistent","namespace":"lifecycle"},"spec":{"tags":[{"from":{"kind":"DockerImage","name":"myregistry.example.com/lifecycle/nodejs-mongo-persistent:1.0"},"importPolicy":{"insecure":true,"scheduled":true},"name":"1.0"}]}}
    openshift.io/image.dockerRepositoryCheck: 2017-10-06T20:10:09Z
    openshift.io/image.insecureRepository: "true"
  creationTimestamp: 2017-10-06T18:50:11Z
  generation: 3
  labels:
    template: nodejs-mongo-persistent
  name: nodejs-mongo-persistent
  namespace: lifecycle
  resourceVersion: "2539112"
  selfLink: /oapi/v1/namespaces/lifecycle/imagestreams/nodejs-mongo-persistent
  uid: 2ebf6428-aac7-11e7-b938-fa163e02a92e
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: myregistry.example.com/lifecycle/nodejs-mongo-persistent:1.0
    generation: 3
    importPolicy:
      insecure: true
      scheduled: true
    name: "1.0"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: docker-registry.default.svc:5000/lifecycle/nodejs-mongo-persistent
  tags:
  - items:
    - created: 2017-10-06T20:10:09Z
      dockerImageReference: myregistry.example.com/lifecycle/nodejs-mongo-persistent@sha256:12ea6466f72fbbbf66d4b53d13fb70820e0dbc85a4f6e82c1cc60352469843b8
      generation: 3
      image: sha256:12ea6466f72fbbbf66d4b53d13fb70820e0dbc85a4f6e82c1cc60352469843b8
    - created: 2017-10-06T18:50:12Z
      dockerImageReference: myregistry.example.com/lifecycle/nodejs-mongo-persistent@sha256:e8134a1a36fc46280f1c5fe259889c2097af0d49b31ed0d87f97247b23d7dedc
      generation: 2
      image: sha256:e8134a1a36fc46280f1c5fe259889c2097af0d49b31ed0d87f97247b23d7dedc
    tag: "1.0"
```

##### Current Result
Pods doesn't run as:
```
2017-10-09 06:43:26 -0400 EDT   2017-10-09 05:37:48 -0400 EDT   47        nodejs-mongo-persistent   DeploymentConfig             Warning   FailedCreate   deployer-controller   Error creating deployer pod: Pod "" is invalid: spec.containers[0].image: Forbidden: this image is prohibited by policy: only images imported into the registry are allowed (openshift/origin-deployer:v3.6.0)
```

##### Expected Result
Deployment working fine.

##### Additional Information
I've tried to configure the IS with the registry to import as secure and it complains about certificates.
I've configured the registry to import with insecure: true in master-config.yaml and it doesn't work either (same error)

```
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: docker.io
  - domainName: '*.docker.io'
  - domainName: '*.redhat.com'
  - domainName: '*.example.com'
    insecure: true
```

**Comment by smarterclayton** [comment]
Could be a bug in treating "openshift/origin-deployer" as coming from docker.io.  @php-coder i thought we had a test case for this?

**Comment by bparees** [comment]
@php-coder bump.

**Comment by php-coder** [comment]
I don't know what to say, except that I've never seen this code before and the only reason of why I added my first comment is that I tried to help to push this issue forward.

**Comment by bparees** [comment]
@mfojtik I seem to recall recently learning that you had a hand in imagepolicy.  Thoughts?

**Comment by bparees** [comment]
@smarterclayton my interpretation of this rule is that it should never reject anything except images w/ the deny-execution annotation:

```
executionRules:
        - name: execution-denied
          matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
```

so how is *anything* being rejected?

it seems like we are mishandling the skipOnResolufionFailure configuration.

**Comment by smarterclayton** [comment]
I think there was a 3.6.0 resolution bug fixed almost immediately after where we were always resolving on some resources.  That was fixed in 3.6.1

**Comment by bparees** [comment]
@smarterclayton https://bugzilla.redhat.com/show_bug.cgi?id=1516496 is on 3.6.1 and still seeing the issue.

**Comment by bparees** [comment]
@e-minguez assuming you aren't otherwise using this rule, can you delete it from your configuration?

```
- name: execution-denied
          matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
```

**Comment by e-minguez** [comment]
So, I think I have this working properly with the following configuration:

```
openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          name: execution-denied
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
        - matchRegistries:
          - docker.io
          - registry.access.redhat.com
          - docker-registry.default.svc:5000
          - 10.111.255.221:5000
          - docker-registry.default.svc
          - 10.111.255.221
          name: allow-images-from-dockerhub
          onResources:
          - resource: '*'
        kind: ImagePolicyConfig
...
imageConfig:
  format: registry.access.redhat.com/openshift3/ose-${component}:${version}
  latest: false
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: docker.io
  - domainName: '*.docker.io'
  - domainName: '*.redhat.com'
  - domainName: docker-registry.default.svc
  - domainName: 10.111.255.221
  - domainName: docker-registry.default.svc:5000
  - domainName: 10.111.255.221:5000
  disableScheduledImport: false
```

And I think the key was modifying the `imageConfig.format` to add the default registry to pull from, so the image includes the full url and matches the "allow-images-from-dockerhub" rule, otherwise I think that information is missing and the rule denies it.

Anyway, I think the documentation is confusing and maybe the default options are confusing as well...

**Comment by smarterclayton** [comment]
Was 'allow-images-from-dockerhub' something you added?  When you specify
execution rules, if all execution rules are "reject" (as in the default
case when only 'execution-denied' exists) then there is an implicit
"allow-all".  If you have both reject and match rules, then there is no
implicit allow all (at least one rule has to match, and zero reject rules
have to match).  If you added 'allow-images-from-dockerhub' that converts
the policy from being:

Allow: not execution-denied

to

Allow: allow-images-from-dockerhub AND not execution-denied

which would fail if it couldn't match the registry.

**Comment by bparees** [comment]
based on the last two updates (the working config and @smarterclayton's explanation of why images were being rejected once the new rule was added), i'm closing this.  @e-minguez please comment back if you have additional questions/concerns.
