### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by cycwll** [openshift/origin#21280]
#### step
1.  Installed the OpenShift cluster by Ansible.

2.  Installed the harbor as docker registry.  domain:  harbor.ctwifi.cn . and validation it is OK.

3.  #oc create secret docker-registry harbor.ctwifi.cn --docker-server=harbor.ctwifi.cn --docker-username=admin --docker-password=admin --docker-email=1234@qq.com 

4.  #oc new-app  --docker-image="harbor.ctwifi.cn/openshift/nginx:1.12" --source-secret='harbor.ctwifi.cn'

#### docker login is OK. such as :
[root@master ~]# docker login harbor.ctwifi.cn
Username (admin): admin
Password:
Login Succeeded

#### docker pull is OK. such as :
#docker pull harbor.ctwifi.cn/openshift/nginx:1.12
Trying to pull repository harbor.ctwifi.cn/openshift/nginx ...
1.12: Pulling from harbor.ctwifi.cn/openshift/nginx
f2aa67a397c4: Pull complete
e3eaf3d87fe0: Pull complete
38cb13c1e4c9: Pull complete
Digest: sha256:09e210fe1e7f54647344d278a8d0dee8a4f59f275b72280e8b5a7c18c560057f
Status: Downloaded newer image for harbor.ctwifi.cn/openshift/nginx:1.12

### But there are problem when oc new-app 
#oc new-app  --docker-image="harbor.ctwifi.cn/openshift/nginx:1.12" --source-secret='harbor.ctwifi.cn'
W1017 16:35:13.562160   55311 dockerimagelookup.go:233] Docker registry lookup failed: Get https://harbor.ctwifi.cn/v2/: **x509: certificate signed by unknown authority**
error: unable to locate any local docker images with name "harbor.ctwifi.cn/openshift/nginx:1.12"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.

#### User OpenShift registry same problem.  
docker login -u dev  -p xPrk7xbJgFXdgdH0D8vKa9dFedM97BjI9KFWSGDglPs docker-registry.default.svc:5000
Login Succeeded

48834 dockerimagelookup.go:233] Docker registry lookup failed: Get https://docker-registry.default.svc:5000/v2/: x509: certificate signed by unknown authority

##### Version
[root@master ~]# oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.ctwifi.cn:8443
openshift v3.10.0+fd501dd-48
kubernetes v1.10.0+b81c8f8

**Comment by cycwll** [comment]
resolved
use parameter --insecure-registry=true

**Comment by cycwll** [comment]
resolved
use parameter --insecure-registry=true

**Comment by xiqning** [comment]
@cycwll  but in the web console still appeare the problem!!!!!

**Comment by cycwll** [comment]
@xiqning  upload your screenshot,please

**Comment by cycwll** [comment]
Are you  configured  /etc/sysconfig/docker ?
OPTIONS='--insecure-registry registry.chamc.intra'

**Comment by xiqning** [comment]
@cycwll The docker registry also used harbor with https ; openshift version is v3.11.16 ; docker login secceeded ; docker pull registry.chamc.intra/techfin/tomcat also no problem ; oc new-app --docker-image=registry.chamc.intra/techfin/tomcat --insecure-registry can create dc,svc and is; but in the web console appeare upon problems!!!    The configfile  /etc/sysconfig/docker  without OPTIONS='--insecure-registry registry.chamc.intra'

**Comment by cycwll** [comment]
You https certificate is official ? or it's youself Issued?

**Comment by xiqning** [comment]
@cycwll  The certificate is self-signed according to the official document of Harbor.
https://github.com/goharbor/harbor/blob/master/docs/configure_https.md

**Comment by cycwll** [comment]
I haven't test it, but I think that's the reason.

**Comment by dajester2013** [comment]
using --insecure-registry is not a solution.  there needs to be a simple way **from the web console** to add a CA for a private registry
