### ISSUE TITLE
Pod can't consume a PVClaim - storage plugins not loaded?

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2433]
I fixed up the docs on creating an example PV + PVC + pod:
https://github.com/openshift/openshift-docs/pull/395

... however something is still not quite working. When I created my pod, it sits in Pending forever and OpenShift has this message in the journal:

`I0522 03:05:47.267683    1654 event.go:203] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"whatever\", Name:\"mypod\", UID:\"46114970-002d-11e5-ae4e-22000ab3877e\", APIVersion:\"v1beta3\", ResourceVersion:\"14869\", FieldPath:\"\"}): reason: 'failedSync' Error syncing pod, skipping: can't use volume plugins for (volume.Spec){Name:(string)myvol VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaimVolumeSource:(*api.PersistentVolumeClaimVolumeSource){ClaimName:(string)claim1 ReadOnly:(bool)false}} PersistentVolumeSource:(api.PersistentVolumeSource){GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> HostPath:(*api.HostPathVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil>}}: no volume plugin matched`

@markturansky Since all the VolumeSource plugins seem to be nil I'm wondering if there is some additional config needed or just a tweak to the code to add the NFSVolumeSource at startup?

**Comment by markturansky** [comment]
They are not all nil.  Your PVClaimVolumeSource is "claim1", which looks correct.

Is the claim and PV bound?

**Comment by sosiouxme** [comment]
I was getting "nil" from seeing ` NFS:(*api.NFSVolumeSource)<nil>` and `no volume plugin matched`

**Comment by markturansky** [comment]
NFS will be nil for this pod.  You are using a claim as your volume (which is not nil).

The claim needs to be bound correctly to the NFS PersistentVolume.  Can you show me that status?

Also, NFS as a persistent volume was merged upstream 15 days ago.  I see it in OpenShift head as a PV.  We need to make sure the version of OpenShift you're using is recent to have this change.  Without it, you won't be able to use NFS as a PersistentVolume (still works as a regular Volume)

**Comment by sosiouxme** [comment]
This was my origin devenv, so very recent. It's blown away, I'll need to recreate.

**Comment by sosiouxme** [comment]
@markturansky I have reproduced at http://pastebin.test.redhat.com/285172 -- any help appreciated

**Comment by markturansky** [comment]
Thanks, I'll run through that and try to find where it's going wrong.

**Comment by markturansky** [comment]
Should be resolved by #2457.

**Comment by sosiouxme** [comment]
@markturansky I'm afraid it still failed, but at least it failed differently. Same scenario:

```
# osc describe pod/mypod                                                                                                                                                                  
Name:                           mypod
[...]Events:
  FirstSeen                             LastSeen                        Count   From                            SubobjectPath   Reason          Message
  Tue, 26 May 2015 19:48:53 +0000       Tue, 26 May 2015 19:48:53 +0000 1       {scheduler }                                    scheduled       Successfully assigned mypod to ip-10-136-62-105
  Tue, 26 May 2015 19:49:06 +0000       Tue, 26 May 2015 19:54:40 +0000 31      {kubelet ip-10-136-62-105}                      failedMount     Unable to mount volumes for pod "mypod_default": unsupported volume
 type
  Tue, 26 May 2015 19:49:06 +0000       Tue, 26 May 2015 19:54:40 +0000 31      {kubelet ip-10-136-62-105}                      failedSync      Error syncing pod, skipping: unsupported volume type

# osc get pod/mypod -o json
{
    "kind": "Pod",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "mypod",
        "namespace": "default",
        [...]
    },
    "spec": {
        "volumes": [
            {
                "name": "pvol",
                "persistentVolumeClaim": {
                    "claimName": "claim1"
                }
            },
            [...]
```

Any pointers what to look for now?

**Comment by markturansky** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8688

I think this PR will fix your issue.

**Comment by sosiouxme** [comment]
@markturansky since this hasn't been rebased into origin yet, I cherry-picked it to try it out. We did the same for enterprise trying to get it into beta4.

https://github.com/sosiouxme/origin/blob/20150528-PVCs/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/volume/nfs/nfs.go

In both tests, things seemed to go well until it came time to actually create the container. Then openshift-node panicked on a nil pointer somewhere down in the volume code.

```
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: E0528 23:32:11.316113   13866 util.go:69] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /usr/lib/golang/src/runtime/asm_amd64.s:401
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /usr/lib/golang/src/runtime/panic.go:387
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /usr/lib/golang/src/runtime/panic.go:42
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /usr/lib/golang/src/runtime/sigpanic_unix.go:26
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/volume/nfs/nfs.go:78
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/volume/nfs/nfs.go:67
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volumes.go:92
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volumes.go:60
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/volume/persistent_claim/persistent_claim.go:81
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volumes.go:92
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volumes.go:112
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:1103
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:317
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/pod_workers.go:106
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/pod_workers.go:115
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /builddir/build/BUILD/openshift-git-10.efd49f5/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/pod_workers.go:136
May 28 23:32:11 node1.osv3.example.com openshift-node[13866]: /usr/lib/golang/src/runtime/asm_amd64.s:2232
```

I'm not sure if this is because we tried a cherry-pick and we're missing the last couple days of kube changes (since origin rebased it), or if there's something else going on. If you have any ideas I'd appreciate them...

**Comment by ironcladlou** [comment]
@sosiouxme 
>In both tests, things seemed to go well until it came time to actually create the container. Then openshift-node panicked on a nil pointer somewhere down in the volume code.

Could [this change](https://github.com/GoogleCloudPlatform/kubernetes/commit/4f88d418c80eb6a395dd99e606e5f545404a17c6) be related? Seems to imply `spec.VolumeSource.NFS=nil` is now an acceptable state, which opens the door for a nil pointer [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/volume/nfs/nfs.go#L71), which seems to jive with the stack trace.

cc @markturansky

**Comment by sosiouxme** [comment]
That's the change we cherry-picked, so I'm sure it's *related* ...

**Comment by markturansky** [comment]
I'll be checking this out sometime today.  busy heads down getting the recycler/scrubber working.  sorry for the delay.

**Comment by markturansky** [comment]
See https://github.com/GoogleCloudPlatform/kubernetes/pull/9055

**Comment by sosiouxme** [comment]
Tested with https://github.com/GoogleCloudPlatform/kubernetes/pull/9055 and it works!! Thanks @markturansky Now we just need to get that merged and rebased into Origin.

**Comment by markturansky** [comment]
Glad to hear that was the fix.  Between this, a number of other upstream PRs, and the new recycling stuff, we've got quite a bit to get merged upstream and rebased downstream.
