### ISSUE TITLE
`osc <command> --help` printing to stderr

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2622]
This will print usage information to stdout and we can pipe it through `less` just fine:

    osc --help | less                  # ok

However, the following won't work as expected:

    osc new-app --help | less          # not ok

I believe we should be always printing help messages to stdout as per the [GNU coding standard](http://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html), unless the user enters an invalid  command or option.

This is actually a problem with [cobra](https://github.com/spf13/cobra), so I've filled an [issue](https://github.com/spf13/cobra/issues/114) there too.

**Comment by fabianofranz** [comment]
@liggitt this is fixed.

**Comment by rhcarvalho** [comment]
@fabianofranz what is the PR that closed this? I can still reproduce the problem with current master branch.
`oc new-app --help` is sending output to stderr instead of stdout.

**Comment by rhcarvalho** [comment]
The upstream issue is still open, and no comments were made there.
Can we reopen this or should I open a new issue in origin?

**Comment by fabianofranz** [comment]
@rhcarvalho my bad, I incorrectly stated this was fixed. @liggitt we should reopen this. I'll work on a PR for Cobra.

**Comment by rhcarvalho** [comment]
@fabianofranz do you have any updates on this?
