### ISSUE TITLE
Switch from referencing podName to ObjectReference in builds.

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#408]
Currently `Build` object references `Pod` doing the actual build by its `name`, the proposition is to use `ObjectReference` instead. See (https://github.com/fabianofranz/origin/commit/cef8f3bd264539ff9a493a939882b8fb5d492e78#commitcomment-8579179) for background.

**Comment by smarterclayton** [comment]
Someone needs to fix this still.

**Comment by soltysh** [comment]
@smarterclayton I'll handle it this week.

**Comment by soltysh** [comment]
But not before #679, I'd like to omit merge conflicts.

**Comment by smarterclayton** [comment]
This is fixed.

**Comment by soltysh** [comment]
@smarterclayton  this is still on my TODO list, and looking at [sources](https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L23) proves that's still not handled properly yet.
