### ISSUE TITLE
Missing IP addresses in node certificates

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#5294]
Currently when we generate certificates for the nodes, we are not specifying the IP address for that certificate. This means that any client which tries to access the endpoint via its IP address will receive an error.

Steps to reproduce:
openshift start --write-config=openshift.local.config --hostname=myNode --public-master=$IP_ADDRESS --master=$IP_ADDRESS

Check the openshift.local.config/node-myNode/server.crt for the IP address.

Without the IP address being available, client may not be able to connect:
`x509: cannot validate certificate for 192.168.122.1 because it doesn't contain any IP SANs`

**Comment by liggitt** [comment]
I think this only applies in the all-in-one case, where we have a way to detect the current IPs. We should add all local IP addresses to the node cert (the same way we add all local IP addresses to the etcd cert)

**Comment by spadgett** [comment]
@mwringe @liggitt Any workaround? This blocks metrics testing.

https://bugzilla.redhat.com/show_bug.cgi?id=1272976

**Comment by mwringe** [comment]
@spadgett Heapster now can support disabling some security checks for the certificate. So I am going to see if we can rebuild Heapster and push out new containers which can enable the work around.

**Comment by liggitt** [comment]
Set hostname to the node ip

**Comment by mwringe** [comment]
Did anyone create a BZ to track this? Or do we need one? This is an important bug we need fixed for metrics to work properly

**Comment by liggitt** [comment]
Being fixed in the installer in https://github.com/openshift/openshift-ansible/pull/609

**Comment by mwringe** [comment]
@liggitt That still doesn't solve the issue for installations which are not done via ansible. I think we still need to fix it for those situations as well.

**Comment by liggitt** [comment]
What installations are these? They need to include the node IP when calling `oadm create-node-config`

**Comment by mwringe** [comment]
I mean when starting OpenShift manually:

openshift start --write-config=openshift.local.config --hostname=$IP_ADDRESS --public-master=$IP_ADDRESS --master=$IP_ADDRESS

Or is the plan here to always force people to set the hostname as the ip address? It might get confusing since if they set the hostname as the actual hostname, then everything works except access to the kubelet endpoints for external services (eg heapster)

**Comment by liggitt** [comment]
this issue is open to add the IP addresses when starting manually. we can track in a BZ if you like.

**Comment by jcantrill** [comment]
Closing in favor of resolving: https://bugzilla.redhat.com/show_bug.cgi?id=1273818 as was opened by qe
