### ISSUE TITLE
Can't start Openshift on OSX

### ISSUE THREAD

**Issue by sdheisenberg** [openshift/origin#5308]
I'm trying to start Openshift from the `v1.0.6` release using [these instructions] (https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary).  A few weeks ago this did work, but I keep getting the error below if executing `sudo ./openshift start` on OSX 10.10.  I can confirm boot2docker is running.  Am I missing something here?

```
$ boot2docker status
running
```

**Startup Log**
```
I1021 15:34:13.704094   72778 plugins.go:70] No cloud provider specified.
I1021 15:34:13.706596   72778 start_master.go:385] Starting master on 0.0.0.0:8443 (v1.0.6)
I1021 15:34:13.706651   72778 start_master.go:386] Public master address is https://192.168.0.2:8443
I1021 15:34:13.706705   72778 start_master.go:390] Using images from "openshift/origin-<component>:v1.0.6"
E1021 15:34:13.709049   72778 reflector.go:180] pkg/admission/serviceaccount/admission.go:101: Failed to list *api.ServiceAccount: Get https://192.168.0.2:8443/api/v1/serviceaccounts: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:13.709108   72778 reflector.go:180] pkg/security/admission/admission.go:59: Failed to list *api.SecurityContextConstraints: Get https://192.168.0.2:8443/api/v1/securitycontextconstraints: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:13.709152   72778 reflector.go:180] pkg/admission/namespace/exists/admission.go:101: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:13.709208   72778 reflector.go:180] pkg/admission/serviceaccount/admission.go:115: Failed to list *api.Secret: Get https://192.168.0.2:8443/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:13.709211   72778 reflector.go:180] pkg/admission/namespace/lifecycle/admission.go:107: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:13.709232   72778 reflector.go:180] pkg/admission/limitranger/admission.go:102: Failed to list *api.LimitRange: Get https://192.168.0.2:8443/api/v1/limitranges: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:13.709502   72778 reflector.go:180] pkg/admission/resourcequota/admission.go:59: Failed to list *api.ResourceQuota: Get https://192.168.0.2:8443/api/v1/resourcequotas: dial tcp 192.168.0.2:8443: connection refused
2015-10-21 15:34:14.178001 I | etcdserver: name = openshift.local
2015-10-21 15:34:14.178040 I | etcdserver: data dir = openshift.local.etcd
2015-10-21 15:34:14.178049 I | etcdserver: member dir = openshift.local.etcd/member
2015-10-21 15:34:14.178057 I | etcdserver: heartbeat = 100ms
2015-10-21 15:34:14.178062 I | etcdserver: election = 1000ms
2015-10-21 15:34:14.178069 I | etcdserver: snapshot count = 0
2015-10-21 15:34:14.178086 I | etcdserver: advertise client URLs = https://192.168.0.2:4001
2015-10-21 15:34:14.216139 I | etcdserver: restarting member 4b729b08b067b568 in cluster 22c8977bb9746cbd at commit index 204
2015-10-21 15:34:14.217731 I | raft: 4b729b08b067b568 became follower at term 3
2015-10-21 15:34:14.217781 I | raft: newRaft 4b729b08b067b568 [peers: [], term: 3, commit: 204, applied: 0, lastindex: 204, lastterm: 3]
2015-10-21 15:34:14.218175 I | etcdserver: set snapshot count to default 10000
2015-10-21 15:34:14.218784 I | etcdserver: starting server... [version: 2.1.2, cluster version: to_be_decided]
2015-10-21 15:34:14.219729 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)
2015-10-21 15:34:14.220446 N | etcdserver: added local member 4b729b08b067b568 [https://192.168.0.2:7001] to cluster 22c8977bb9746cbd
2015-10-21 15:34:14.220553 N | etcdserver: set the initial cluster version to 2.1.0
I1021 15:34:14.220788   72778 etcd.go:68] Started etcd at 192.168.0.2:4001
I1021 15:34:14.257037   72778 run_components.go:182] Using default project node label selector:
E1021 15:34:14.281491   72778 reflector.go:180] pkg/project/cache/cache.go:102: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711188   72778 reflector.go:180] pkg/admission/serviceaccount/admission.go:115: Failed to list *api.Secret: Get https://192.168.0.2:8443/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711395   72778 reflector.go:180] pkg/admission/namespace/lifecycle/admission.go:107: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711449   72778 reflector.go:180] pkg/admission/serviceaccount/admission.go:101: Failed to list *api.ServiceAccount: Get https://192.168.0.2:8443/api/v1/serviceaccounts: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711496   72778 reflector.go:180] pkg/security/admission/admission.go:59: Failed to list *api.SecurityContextConstraints: Get https://192.168.0.2:8443/api/v1/securitycontextconstraints: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711533   72778 reflector.go:180] pkg/admission/namespace/exists/admission.go:101: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711541   72778 reflector.go:180] pkg/admission/limitranger/admission.go:102: Failed to list *api.LimitRange: Get https://192.168.0.2:8443/api/v1/limitranges: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:14.711955   72778 reflector.go:180] pkg/admission/resourcequota/admission.go:59: Failed to list *api.ResourceQuota: Get https://192.168.0.2:8443/api/v1/resourcequotas: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.283236   72778 reflector.go:180] pkg/project/cache/cache.go:102: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
2015-10-21 15:34:15.423449 I | raft: 4b729b08b067b568 is starting a new election at term 3
2015-10-21 15:34:15.423606 I | raft: 4b729b08b067b568 became candidate at term 4
2015-10-21 15:34:15.431511 I | raft: 4b729b08b067b568 received vote from 4b729b08b067b568 at term 4
2015-10-21 15:34:15.431553 I | raft: 4b729b08b067b568 became leader at term 4
2015-10-21 15:34:15.431570 I | raft: raft.node: 4b729b08b067b568 elected leader 4b729b08b067b568 at term 4
2015-10-21 15:34:15.432434 I | etcdserver: published {Name:openshift.local ClientURLs:[https://192.168.0.2:4001]} to cluster 22c8977bb9746cbd
I1021 15:34:15.692011   72778 master.go:229] Started Kubernetes API at 0.0.0.0:8443/api/v1beta3 (deprecated)
I1021 15:34:15.692049   72778 master.go:229] Started Kubernetes API at 0.0.0.0:8443/api/v1
I1021 15:34:15.692055   72778 master.go:229] Started Origin API at 0.0.0.0:8443/osapi/v1beta3
I1021 15:34:15.692060   72778 master.go:229] Started Origin API at 0.0.0.0:8443/oapi/v1
I1021 15:34:15.692066   72778 master.go:229] Started OAuth2 API at 0.0.0.0:8443/oauth
I1021 15:34:15.692071   72778 master.go:229] Started Login endpoint at 0.0.0.0:8443/login
I1021 15:34:15.692076   72778 master.go:229] Started Web Console 0.0.0.0:8443/console/
I1021 15:34:15.692081   72778 master.go:229] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
E1021 15:34:15.712932   72778 reflector.go:180] pkg/admission/serviceaccount/admission.go:101: Failed to list *api.ServiceAccount: Get https://192.168.0.2:8443/api/v1/serviceaccounts: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.712932   72778 reflector.go:180] pkg/admission/limitranger/admission.go:102: Failed to list *api.LimitRange: Get https://192.168.0.2:8443/api/v1/limitranges: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.712961   72778 reflector.go:180] pkg/security/admission/admission.go:59: Failed to list *api.SecurityContextConstraints: Get https://192.168.0.2:8443/api/v1/securitycontextconstraints: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.713003   72778 reflector.go:180] pkg/admission/resourcequota/admission.go:59: Failed to list *api.ResourceQuota: Get https://192.168.0.2:8443/api/v1/resourcequotas: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.713002   72778 reflector.go:180] pkg/admission/namespace/lifecycle/admission.go:107: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.713017   72778 reflector.go:180] pkg/admission/serviceaccount/admission.go:115: Failed to list *api.Secret: Get https://192.168.0.2:8443/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 192.168.0.2:8443: connection refused
E1021 15:34:15.713025   72778 reflector.go:180] pkg/admission/namespace/exists/admission.go:101: Failed to list *api.Namespace: Get https://192.168.0.2:8443/api/v1/namespaces: dial tcp 192.168.0.2:8443: connection refused
2015-10-21 15:34:16.187417 I | skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:53 [rcache 0]
2015-10-21 15:34:16.187454 I | skydns: ready for queries on cluster.local. for udp4://0.0.0.0:53 [rcache 0]
I1021 15:34:16.285251   72778 run_components.go:177] DNS listening at 0.0.0.0:53
Generating node credentials ...
I1021 15:34:16.286129   72778 start_master.go:516] Controllers starting (*)
I1021 15:34:17.321309   72778 nodecontroller.go:112] Sending events to api server.
I1021 15:34:17.322572   72778 start_master.go:543] Started Kubernetes Controllers
I1021 15:34:18.158721   72778 start_master.go:562] Started Origin Controllers
Created node config for <user>.local in openshift.local.config/node-<user>.local
I1021 15:34:18.498491   72778 start_node.go:175] Starting a node connected to https://192.168.0.2:8443
I1021 15:34:18.512983   72778 start_node.go:267] Starting node <user>.local (v1.0.6)
E1021 15:34:18.516795   72778 node.go:87] WARNING: Docker could not be reached at unix:///var/run/docker.sock.  Docker must be installed and running to start containers.
dial unix /var/run/docker.sock: no such file or directory
W1021 15:34:18.518994   72778 server.go:407] setting OOM scores is unsupported in this build
I1021 15:34:18.520088   72778 server.go:704] Watching apiserver
F1021 15:34:18.524351   72778 node.go:141] failed to create kubelet: cAdvisor is unsupported in this build
W1021 15:34:18.524746   72778 node.go:184] WARNING: Could not modify iptables. You must run this process as root to use the service proxy: failed to initialize iptables: error creating chain "KUBE-PORTALS-CONTAINER": exec: "iptables": executable file not found in $PATH:
E1021 15:34:18.556078   72778 reflector.go:180] pkg/kubelet/kubelet.go:195: Failed to list *api.Node: Get https://192.168.0.2:8443/api/v1/nodes?fieldSelector=metadata.name%3D<user>.local: dial tcp 192.168.0.2:8443: too many open files
```

**Comment by smarterclayton** [comment]
Fixed in https://github.com/openshift/origin/pull/5298

**Comment by sdheisenberg** [comment]
Hmm, I'm still getting this error after syncing with master and running a `make clean build`

```
$ git show
commit c77d8eff9eeb7c69f22acc11124b576c3cab959a
Merge: 1314bb7 fcf4580
Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>
Date:   Thu Oct 22 15:41:59 2015 -0400

    Merge pull request #5309 from spadgett/scaling-controls-block-elem

    Merged by openshift-bot
```

**Startup sample output**
```
Get http://unix.sock/_ping: dial unix /var/run/docker.sock: no such file or directory
W1022 14:09:10.727114    6682 server.go:472] setting OOM scores is unsupported in this build
W1022 14:09:10.727211    6682 iptables.go:140] Error checking iptables version, assuming version at least 1.4.11: exec: "iptables": executable file not found in $PATH
I1022 14:09:10.727668    6682 server.go:801] Watching apiserver
F1022 14:09:10.731654    6682 node.go:148] failed to create kubelet: cAdvisor is unsupported in this build
W1022 14:09:10.731865    6682 node.go:225] WARNING: Could not modify iptables. You must run this process as root to use the service proxy: failed to initialize iptables: error creating chain "KUBE-PORTALS-CONTAINER": exec: "iptables": executable file not found in $PATH:
```

**Comment by smarterclayton** [comment]
OpenShift nodes have to run on Linux.  You can't run `openshift start` on a Mac - you have to configure it separately.  Generally, running a container inside a VM is the way to go - however boot2docker doesn't support the necessary kernel features to run a Kubernetes VM.

**Comment by smarterclayton** [comment]
To run a *full* Kubernetes install.

**Comment by jtblin** [comment]
@smarterclayton it'd be great to update the docs because they don't say that you can't run `openshift start` on Mac: https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary

**Comment by smarterclayton** [comment]
I think this note is too subtle :)

"These are Linux, Windows, or Mac OS X 64-bit binaries; note that the Mac
and Windows versions are for the CLI only."

On Thu, Nov 5, 2015 at 6:09 AM, Jerome Touffe-Blin <notifications@github.com

**Comment by smarterclayton** [comment]
A challenge of the docs is that the "prerequisites" page is something most
folks would skip.  we'll try to add better docs here.

**Comment by HometownRocker** [comment]
Is this statement accurate?

** The release archives for Linux and Mac OS X contain the server binary openshift which is an all-in-one OpenShift installation.  **

The statement is in the second paragraph of Method 2 (Downloading the Binary) located at https://docs.openshift.org/latest/getting_started/administrators.html

**Comment by smarterclayton** [comment]
Actually, this has changed now that the zips have been updated.  We only
build the server binaries for linux now, but the client tools zips are for
each platform.
