### ISSUE TITLE
dc describer highlights the latest deployment

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7996]
It should highlight the active, right?
```
Deployment #5 (latest):
	Name:		docker-registry-5
	Created:	45 minutes ago
	Status:		Failed
	Replicas:	0 current / 0 desired
	Selector:	deployment=docker-registry-5,deploymentconfig=docker-registry,docker-registry=default
	Labels:		docker-registry=default,openshift.io/deployment-config.name=docker-registry
	Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Deployment #4:
	Created:	2 hours ago
	Status:		Failed
	Replicas:	0 current / 0 desired
Deployment #3:
	Created:	2 hours ago
	Status:		Failed
	Replicas:	0 current / 0 desired
Deployment #2:
	Created:	3 hours ago
	Status:		Failed
	Replicas:	0 current / 0 desired
Deployment #1:
	Created:	3 hours ago
	Status:		Complete
	Replicas:	1 current / 1 desired
```
@fabianofranz @smarterclayton @ironcladlou

**Comment by soltysh** [comment]
:+1: maybe active could be the first on the list and then old deployments section with less details - maybe one-liners or alike.

**Comment by kargakis** [comment]
I am ok with the order of the deployments. I believe it would be more intuitive to just highlight the active deployment wherever that may be. One-liners for the rest of the deployments sounds good to me.

**Comment by smarterclayton** [comment]
We should be following the logic of status as much as possible.

**Comment by kargakis** [comment]
> We should be following the logic of status as much as possible.

So we should start truncating older deployments here too.

**Comment by mfojtik** [comment]
@kargakis or just display them on single line.

**Comment by kargakis** [comment]
Single line for the inactive deployments. Also have a look at how `oc status` works. It always show the three latest deployments.

**Comment by mfojtik** [comment]
@kargakis I believe this is now fixed? I updated the describer to show just latest 3 deployments.

**Comment by kargakis** [comment]
@mfojtik no it's still not fixed
```
Deployment #3 (latest):
	Name:		database-3
	Created:	18 seconds ago
	Status:		Failed
	Replicas:	0 current / 0 desired
	Selector:	deployment=database-3,deploymentconfig=database,name=database
	Labels:		openshift.io/deployment-config.name=database,template=application-template-stibuild
	Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Deployment #2:
	Created:	about a minute ago
	Status:		Complete
	Replicas:	1 current / 1 desired
Deployment #1:
	Created:	6 minutes ago
	Status:		Complete
	Replicas:	0 current / 0 desired
```
We still highlight the latest instead of the active.

**Comment by kargakis** [comment]
@mfojtik this needs a follow-up. Should we open a new issue to track that change?

**Comment by mfojtik** [comment]
@kargakis working on it (i will create issue)
