### ISSUE TITLE
osc create minion fails due to adding namespace

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#802]
If I create some json for adding a minion, it succeeds via curl -X POST, but fails via osc create -f which apparently adds the "namespace" parameter a bit too indiscriminately resulting in the error "namespace: invalid value 'default'". The same error results if I do so manually with curl e.g. http://pastebin.com/bEfecgSu

BTW it would be really nice if there were an osc option such that I could see what the API request and response looked like. It would be more obvious what's going on in cases like this.

@pravisankar said he would work on this

**Comment by pravisankar** [comment]
This issue was fixed in the upstream: https://github.com/GoogleCloudPlatform/kubernetes/pull/3961
jhonce/markturansky will pull this pr into openshift for beta1 release.
Above fix will only suppress the error, proper fix to handle namespace scoping is currently worked on by derek, WIP prs: https://github.com/GoogleCloudPlatform/kubernetes/pull/3613 (new namespace object), https://github.com/GoogleCloudPlatform/kubernetes/pull/3944 (targeted for beta2).

**Comment by smarterclayton** [comment]
Should be fixed - reopen if not

**Comment by sosiouxme** [comment]
@thoraxe says it's not fixed.

"fix will only suppress the error" -- where is it suppressed? Should we expect "osc create -f" to work with minion defined in JSON or not?

**Comment by smarterclayton** [comment]
Fixed in what?  Master?

----- Original Message -----

**Comment by sosiouxme** [comment]
With cec9653ffcc1b4befceb78d3d16a1434f4c9add2:

```
$ cat > minion.json
{
  "id": "ose3-node1.example.com",
  "kind": "Minion",
  "apiVersion": "v1beta1",
}
$ osc create -f minion.json
F0202 20:34:53.584775    1489 create.go:78] minion "ose3-node1.example.com" is invalid: metadata.namespace: invalid value 'default': namespace is not allowed on this type
```

**Comment by smarterclayton** [comment]
Derek's big changes landed today, I'm going to try and reuse.   That was the right fix anyway

**Comment by pravisankar** [comment]
@sosiouxme adding more context
osc/kubectl is passing 'default' namespace to all resources including 'node'
https://github.com/GoogleCloudPlatform/kubernetes/pull/3961 removed namespace validation for 'node' creation.
Later on, there was another change...we introduced ValidateObjectMeta() in the ValidateMinion which expects namespace *not* to be passed for 'node' resource.
I'm hoping Derek's change will ensure POST create on node resource will not pass namespace (RESTScope on node will be root/cluster instead of namespace).
I will test the node creation on latest k8s code.

**Comment by pravisankar** [comment]
Tested node creation on latest k8s code (has Derek's changes) and it *worked* without any issues.
@smarterclayton should we rebase k8s code again?
coping @jwhonce @markturansky

**Comment by pravisankar** [comment]
@jwhonce @markturansky we need to rebase k8s one more time

**Comment by jwhonce** [comment]
@pravisankar That validation code is not on master so I believe we are covered.

**Comment by pravisankar** [comment]
@jwhonce validation code is on origin master (origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation/validation.go), we need derek's REST mapper scope changes(8b2eeafd4985c68275315ae), need to pull around 28 commits from k8s upstream.

**Comment by sosiouxme** [comment]
@smarterclayton would be a little embarrassing not to have for beta1. though specifying --nodes isn't so bad if we don't want to rock the boat just now.

**Comment by pravisankar** [comment]
@sosiouxme clayton merged needed changes, we should be able to add/remove nodes using osc.

**Comment by smarterclayton** [comment]
Has anyone tested?

**Comment by pravisankar** [comment]
I've just tested on my local machine and it worked as expected.
