### ISSUE TITLE
Automated sync vendored Kubernetes with OpenShift Kubernetes fork

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#8289]
Currently the vendored Kubernetes is out of sync with the OpenShift Kubernetes fork. This makes it pretty hard to build any utilities that use the OpenShift/Kubernetes go client & API, SCC being the big sticking point. Speaking to @deads2k on IRC it would be awesome if there was a process to ensure the OpenShift Kubernetes fork is continuously synced with the vendored Kubernetes.

**Comment by deads2k** [comment]
I think the best we can do this week is sync'ing the fork.

@liggitt Do we have any picks outstanding that you know of?

**Comment by jimmidyson** [comment]
There's no rush for now as I've just manually copied over the vendored Kubernetes to my project instead. Of course would prefer to be able to use glide to just point to the fork & all just work (like it did for 1.1.3 btw) but no mad rush.

**Comment by vbehar** [comment]
Hi,

I'm also writing tools on top of the openshift API, and "vendoring" openshift code and thus the forked kubernetes code.
It's always a mess, and we end up with a big "cp -r" of the vendored kubernetes code.

I tried to update our vendored dependencies yesterday (with the 1.1.5 tag), and indeed got errors because the kubernetes code in openshift's godeps is not in sync with the commit declared in godeps.json

My solution (that worked) was to:
- git clone github.com/openshift/kubernetes
- git clone github.com/openshift/origin
- find the commit in origin where the k8s commit was updated in godeps.json -> https://github.com/openshift/origin/commit/1fd827d38ba7132f22dfa928a7d5e7e7f72734a0
- git co 1fd827d38ba7132f22dfa928a7d5e7e7f72734a0 (in origin)
- godep restore (from origin)
- godep save (in my project)

but it would be easier if the k8s code included in origin was in sync with the commit referenced in godeps.json ;-)

the issue if I tried to "godep restore" from the 1.1.5 tag was:

```
# github.com/openshift/origin/pkg/cmd/cli/describe
../../openshift/origin/pkg/cmd/cli/describe/deployments.go:269: too many arguments in call to kubectl.DescribePodTemplate
```

which is related to a change in https://github.com/openshift/origin/pull/8177

I think for a start, if you could make sure to sync for the releases, it would be enough for most people.

**Comment by mfojtik** [comment]
@jimmidyson is this fixed now? I think the best we can do every time this happens is to keep the fork in sync.

@stevekuznetsov @deads2k is there something we can do to automate the sync (iow. every pick merged to origin will be automatically added to the fork, etc..)

**Comment by jimmidyson** [comment]
@mfojtik AFAIK this is not fixed. PRs still need to be sent to openshift/origin vendored deps & upstream (if applicable) & then reconciled on rebase.

**Comment by stevekuznetsov** [comment]
Best choice we have is to add the Kube code as a git submodule

**Comment by danmcp** [comment]
Closing this as I don't think it has any well defined action.  There is ongoing work to improve/remove the need for rebases.

**Comment by deads2k** [comment]
> Closing this as I don't think it has any well defined action. There is ongoing work to improve/remove the need for rebases.

This is intended to go in the other direction: make openshift/kubernetes match the code in openshift/origin.  It can be done by applying all upstream patches against openshift/kubernetes and then doing an update to godeps.json.

**Comment by kargakis** [comment]
@mfojtik is this still an issue now that the publishing bot is running for Openshift?
