### ISSUE TITLE
EBS dynamically provisioned disk doesn't get right mount point?

### ISSUE THREAD

**Issue by danni** [openshift/origin#8336]
Dynamically created EBS storage doesn't appear to be mountable because something (Kubernetes?) appears to mount it in the wrong place.

```
# oc get pv
NAME           CAPACITY   ACCESSMODES   STATUS    CLAIM                         REASON    AGE
pv-aws-bmg1v   20Gi       RWO           Bound     logging/logging-es-u4vgdo2e             3h

# oc export pv pv-aws-bmg1v
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    volume.alpha.kubernetes.io/storage-class: foo
    volume.experimental.kubernetes.io/provisioning-required: volume.experimental.kubernetes.io/provisioning-completed
  creationTimestamp: null
  generateName: pv-aws-
  labels:
    failure-domain.beta.kubernetes.io/region: ap-southeast-2
    failure-domain.beta.kubernetes.io/zone: ap-southeast-2c
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-southeast-2c/vol-8538cc5e
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: logging-es-u4vgdo2e
    namespace: logging
    resourceVersion: "70409"
    uid: 680a9909-f89e-11e5-ad52-06be9777f317
  persistentVolumeReclaimPolicy: Delete
status: {}
```

Pod fails to load with the following:
```
I0402 09:51:31.224842   12559 nsenter_mount.go:174] findmnt command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /bin/findmnt -o target --noheadings --target /var/lib/origin/openshift.local.volumes/pods/f5db9dc5-f8b7-11e5-9b7a-0a6850b1f93f/volumes/kubernetes.io~aws-ebs/pv-aws-bmg1v]
I0402 09:51:31.234237   12559 nsenter_mount.go:179] Failed findmnt command: exit status 1
I0402 09:51:31.234276   12559 aws_ebs.go:229] PersistentDisk set up: /var/lib/origin/openshift.local.volumes/pods/f5db9dc5-f8b7-11e5-9b7a-0a6850b1f93f/volumes/kubernetes.io~aws-ebs/pv-aws-bmg1v false <nil>
I0402 09:51:31.234304   12559 aws_util.go:52] AttachAndMountDisk(...) called for PD "aws://ap-southeast-2c/vol-8538cc5e". Will block for existing operations, if any. (globalPDPath="/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-2c/vol-8538cc5e")
I0402 09:51:31.234322   12559 keymutex.go:49] LockKey(...) called for id "aws://ap-southeast-2c/vol-8538cc5e"
I0402 09:51:31.234339   12559 keymutex.go:52] LockKey(...) for id "aws://ap-southeast-2c/vol-8538cc5e" completed.
I0402 09:51:31.234348   12559 aws_util.go:58] AttachAndMountDisk(...) called for PD "aws://ap-southeast-2c/vol-8538cc5e". Awake and ready to execute. (globalPDPath="/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-2c/vol-8538cc5e")
I0402 09:51:31.234582   12559 aws.go:546] Zone not specified in configuration file; querying AWS metadata service
I0402 09:51:31.237211   12559 log_handler.go:33] AWS request: ec2 DescribeInstances
I0402 09:51:31.301200   12559 log_handler.go:33] AWS request: ec2 DescribeInstances
E0402 09:51:31.359133   12559 aws.go:676] Tag "KubernetesCluster" not found; Kuberentes may behave unexpectedly.
I0402 09:51:31.359162   12559 aws.go:683] AWS cloud - no tag filtering
I0402 09:51:31.359227   12559 log_handler.go:33] AWS request: ec2 DescribeInstances
W0402 09:51:31.410040   12559 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-8538cc5e
I0402 09:51:31.410160   12559 log_handler.go:33] AWS request: ec2 DescribeVolumes
E0402 09:51:31.453355   12559 aws.go:1081] endAttaching on non-allocated device
I0402 09:51:31.453392   12559 aws_util.go:208] Successfully attached EBS Disk "aws://ap-southeast-2c/vol-8538cc5e".
I0402 09:51:31.453410   12559 nsenter_mount.go:174] findmnt command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /bin/findmnt -o target --noheadings --target /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-2c/vol-8538cc5e]
I0402 09:51:31.467225   12559 nsenter_mount.go:179] Failed findmnt command: exit status 1
I0402 09:51:31.490048   12559 nsenter_mount.go:114] nsenter Mounting /dev/xvdba /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-2c/vol-8538cc5e ext4 [defaults]
I0402 09:51:31.490090   12559 nsenter_mount.go:117] Mount command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /bin/mount -t ext4 -o defaults /dev/xvdba /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-2c/vol-8538cc5e]
I0402 09:51:31.498226   12559 nsenter_mount.go:121] Output from mount command: mount: mount point /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-2c/vol-8538cc5e does not exist
```

**Comment by danni** [comment]
I should add this is containerized on CentOS atomic, installed with a hacked up openshift-ansible.

**Comment by andrewklau** [comment]
@danni I think your issue is related to and fixed by #8501

**Comment by danni** [comment]
Is that in Origin 1.1.6? I upgraded but am still getting no joy.

**Comment by danni** [comment]
For reference, I've worked around this by doing the following:
* Creating the directory with `mkdir -p var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/aws-ebs/mounts/<vol id>`
* Creating the disk label with fdisk (that was appearing in the logs, not sure if it was actually required)
* Allowing write permission to non-root to the directory

**Comment by andrewklau** [comment]
Origin 1.2.0-rc-1 seems to have the fix but doesn't fix the issue, also the workaround you found earlier no longer seems to be valid, directory paths seem to have changed.

**Comment by andrewklau** [comment]
I re-ran a new install and this seems to be fixed in v1.2.0-rc1 (at least for me now)
