### ISSUE TITLE
openshift build error with log `Failed to push image: Error parsing HTTP response: unexpected end of JSON input: ""`

### ISSUE THREAD

**Issue by dragon9783** [openshift/origin#8368]
Could anyone help with the following build error please?
[Description]
openshift build error with log `Failed to push image: Error parsing HTTP response: unexpected end of JSON input: ""`
##### Environments

etcd *3
master *3 (containerized)
node *3 (containerized)
lb *1
##### Version

openshift: v1.1.4
oc:            v1.1.4
##### Steps To Reproduce
1. oc new-app https://github.com/dragon9783/docker-2048.git
2. oc status -v
##### Current Result

build error
##### build pod log

```
I0406 07:47:09.436632       1 builder.go:46] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"docker-2048-1","namespace":"liujie15","selfLink":"/oapi/v1/namespaces/liujie15/builds/docker-2048-1","uid":"c58d09ff-fbcb-11e5-a9f3-fa163d0e0615","resourceVersion":"32137","creationTimestamp":"2016-04-06T07:47:11Z","labels":{"app":"docker-2048","buildconfig":"docker-2048","openshift.io/build-config.name":"docker-2048"},"annotations":{"openshift.io/build.number":"1"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/dragon9783/docker-2048.git"},"secrets":[]},"strategy":{"type":"Docker","dockerStrategy":{"from":{"kind":"DockerImage","name":"alpine@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0"}}},"output":{"to":{"kind":"DockerImage","name":"172.30.142.230:5000/liujie15/docker-2048:latest"},"pushSecret":{"name":"builder-dockercfg-fopux"}},"resources":{},"postCommit":{}},"status":{"phase":"New","outputDockerImageReference":"172.30.142.230:5000/liujie15/docker-2048:latest","config":{"kind":"BuildConfig","namespace":"liujie15","name":"docker-2048"}}}

I0406 07:47:09.437492       1 builder.go:57] Master version "v1.1.4", Builder version "v1.1.4"
I0406 07:47:09.437929       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:9223372036854775807, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:9223372036854775807}
I0406 07:47:09.438081       1 source.go:197] Downloading "https://github.com/dragon9783/docker-2048.git" ...
I0406 07:47:09.438110       1 source.go:109] git ls-remote https://github.com/dragon9783/docker-2048.git --heads
I0406 07:47:09.438156       1 repository.go:290] Executing git ls-remote https://github.com/dragon9783/docker-2048.git --heads
I0406 07:47:12.375763       1 source.go:208] Cloning source from https://github.com/dragon9783/docker-2048.git
I0406 07:47:12.375809       1 repository.go:290] Executing git clone --quiet --recursive https://github.com/dragon9783/docker-2048.git /tmp/docker-build797095121
I0406 07:48:56.751527       1 repository.go:290] Executing git config --get remote.origin.url
I0406 07:48:56.753087       1 repository.go:315] Out: https://github.com/dragon9783/docker-2048.git
I0406 07:48:56.753117       1 repository.go:290] Executing git rev-parse --abbrev-ref HEAD
I0406 07:48:56.755517       1 repository.go:315] Out: master
I0406 07:48:56.755542       1 repository.go:290] Executing git rev-parse --verify HEAD
I0406 07:48:56.757069       1 repository.go:315] Out: dd113f9dba918e3bc6f757c073570f519c8fd94e
I0406 07:48:56.757097       1 repository.go:290] Executing git --no-pager show -s --format=%an HEAD
I0406 07:48:56.759155       1 repository.go:315] Out: dragon9783
I0406 07:48:56.759195       1 repository.go:290] Executing git --no-pager show -s --format=%ae HEAD
I0406 07:48:56.761252       1 repository.go:315] Out: dragon9783@126.com
I0406 07:48:56.761297       1 repository.go:290] Executing git --no-pager show -s --format=%cn HEAD
I0406 07:48:56.763328       1 repository.go:315] Out: dragon9783
I0406 07:48:56.763355       1 repository.go:290] Executing git --no-pager show -s --format=%ce HEAD
I0406 07:48:56.765227       1 repository.go:315] Out: dragon9783@126.com
I0406 07:48:56.765270       1 repository.go:290] Executing git --no-pager show -s --format=%ad HEAD
I0406 07:48:56.767301       1 repository.go:315] Out: Thu Mar 31 10:35:39 2016 +0800
I0406 07:48:56.767347       1 repository.go:290] Executing git --no-pager show -s --format=%<(80,trunc)%s HEAD
I0406 07:48:56.769079       1 repository.go:315] Out: Update index.html
I0406 07:48:56.769119       1 common.go:86] Setting build revision to &api.GitSourceRevision{Commit:"dd113f9dba918e3bc6f757c073570f519c8fd94e", Author:api.SourceControlUser{Name:"dragon9783", Email:"dragon9783@126.com"}, Committer:api.SourceControlUser{Name:"dragon9783", Email:"dragon9783@126.com"}, Message:"Update index.html"}
I0406 07:48:56.823675       1 repository.go:290] Executing git config --get remote.origin.url
I0406 07:48:56.826276       1 repository.go:315] Out: https://github.com/dragon9783/docker-2048.git
I0406 07:48:56.826387       1 repository.go:290] Executing git rev-parse --abbrev-ref HEAD
I0406 07:48:56.828929       1 repository.go:315] Out: master
I0406 07:48:56.828984       1 repository.go:290] Executing git rev-parse --verify HEAD
I0406 07:48:56.831346       1 repository.go:315] Out: dd113f9dba918e3bc6f757c073570f519c8fd94e
I0406 07:48:56.831380       1 repository.go:290] Executing git --no-pager show -s --format=%an HEAD
I0406 07:48:56.834444       1 repository.go:315] Out: dragon9783
I0406 07:48:56.834475       1 repository.go:290] Executing git --no-pager show -s --format=%ae HEAD
I0406 07:48:56.837667       1 repository.go:315] Out: dragon9783@126.com
I0406 07:48:56.837706       1 repository.go:290] Executing git --no-pager show -s --format=%cn HEAD
I0406 07:48:56.840465       1 repository.go:315] Out: dragon9783
I0406 07:48:56.840499       1 repository.go:290] Executing git --no-pager show -s --format=%ce HEAD
I0406 07:48:56.843060       1 repository.go:315] Out: dragon9783@126.com
I0406 07:48:56.843093       1 repository.go:290] Executing git --no-pager show -s --format=%ad HEAD
I0406 07:48:56.845719       1 repository.go:315] Out: Thu Mar 31 10:35:39 2016 +0800
I0406 07:48:56.845757       1 repository.go:290] Executing git --no-pager show -s --format=%<(80,trunc)%s HEAD
I0406 07:48:56.848857       1 repository.go:315] Out: Update index.html
I0406 07:48:56.849545       1 docker.go:78] Starting Docker build from build config docker-2048-1 ...
Step 1 : FROM alpine@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0
 ---> b66121b7b9c0
Step 2 : MAINTAINER alex <alexwhen@gmail.com>
 ---> Using cache
 ---> 08cb12faf9cd
Step 3 : RUN apk --update add nginx
 ---> Using cache
 ---> 50d2a8148690
Step 4 : COPY 2048 /usr/share/nginx/html
 ---> Using cache
 ---> 7f8c86b6b3f9
Step 5 : EXPOSE 80
 ---> Using cache
 ---> fd261f34b4cd
Step 6 : CMD nginx -g daemon off;
 ---> Using cache
 ---> cd8f0de804d5
Step 7 : ENV "OPENSHIFT_BUILD_NAME" "docker-2048-1" "OPENSHIFT_BUILD_NAMESPACE" "liujie15" "OPENSHIFT_BUILD_SOURCE" "https://github.com/dragon9783/docker-2048.git" "OPENSHIFT_BUILD_COMMIT" "dd113f9dba918e3bc6f757c073570f519c8fd94e"
 ---> Using cache
 ---> 856f3bad7986
Step 8 : LABEL "io.openshift.build.commit.author" "dragon9783 \u003cdragon9783@126.com\u003e" "io.openshift.build.commit.date" "Thu Mar 31 10:35:39 2016 +0800" "io.openshift.build.commit.id" "dd113f9dba918e3bc6f757c073570f519c8fd94e" "io.openshift.build.commit.ref" "master" "io.openshift.build.commit.message" "Update index.html" "io.openshift.build.source-location" "https://github.com/dragon9783/docker-2048.git"
 ---> Using cache
 ---> 863c886f7127
Successfully built 863c886f7127
I0406 07:48:57.132599       1 cfg.go:45] Locating docker auth for image 172.30.142.230:5000/liujie15/docker-2048:latest and type PUSH_DOCKERCFG_PATH
I0406 07:48:57.132931       1 cfg.go:83] Using serviceaccount user for Docker authentication for image 172.30.142.230:5000/liujie15/docker-2048:latest
I0406 07:48:57.132953       1 docker.go:116] Authenticating Docker push with user "serviceaccount"
I0406 07:48:57.132962       1 docker.go:118] Pushing image 172.30.142.230:5000/liujie15/docker-2048:latest ...
F0406 07:48:57.167005       1 builder.go:204] Error: build error: Failed to push image: Error parsing HTTP response: unexpected end of JSON input: ""
```
##### Intergrated Registry log:

```
time="2016-04-06T07:48:58.091796634Z" level=debug msg="authorizing request" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=0f0b8eb7-1c49-4bd6-be08-367bd8652cff http.request.method=GET http.request.remoteaddr="10.1.1.1:36952" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe 
time="2016-04-06T07:48:58.091960494Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=0f0b8eb7-1c49-4bd6-be08-367bd8652cff http.request.method=GET http.request.remoteaddr="10.1.1.1:36952" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe 
10.1.1.1 - - [06/Apr/2016:07:48:58 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
time="2016-04-06T07:48:58.101659953Z" level=debug msg="authorizing request" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
time="2016-04-06T07:48:58.1018503Z" level=debug msg="Origin auth: checking for access to repository:liujie15/docker-2048:pull" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
time="2016-04-06T07:48:58.114913532Z" level=error msg="OpenShift client error: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
time="2016-04-06T07:48:58.114998199Z" level=error msg="error checking authorization: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
time="2016-04-06T07:48:58.115072797Z" level=error msg="error authorizing context: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
10.1.1.1 - - [06/Apr/2016:07:48:58 +0000] "POST /v2/liujie15/docker-2048/blobs/uploads/ HTTP/1.1" 400 0 "" "docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
```

`oc get secrets`

```
builder-dockercfg-fopux    kubernetes.io/dockercfg               1         14m
builder-token-1z3id        kubernetes.io/service-account-token   3         14m
builder-token-cdz82        kubernetes.io/service-account-token   3         14m
default-dockercfg-uwhek    kubernetes.io/dockercfg               1         14m
default-token-26gnr        kubernetes.io/service-account-token   3         14m
default-token-jlnpw        kubernetes.io/service-account-token   3         14m
deployer-dockercfg-378gv   kubernetes.io/dockercfg               1         14m
deployer-token-a74ao       kubernetes.io/service-account-token   3         14m
deployer-token-ajsjv       kubernetes.io/service-account-token   3         14m
```
##### Expected Result

build success
##### Additional Information

`$ oadm diagnostics` command if possible]

```
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'liujie15/openshift-container-deploy2:8443/system:admin'
[Note] Systemd not available, skipping unit discovery.

[Note] Running diagnostic: ConfigContexts[default/openshift-container-deploy2:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'default/openshift-container-deploy2:8443/system:admin':
       The server URL is 'https://openshift-container-deploy2:8443'
       The user authentication is 'system:admin/openshift-container-deploy2:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [liujie15 default management-infra openshift openshift-infra]

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       Info:  Service account token successfully authenticated to master

       ERROR: [DP1014 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:168]
              Request to integrated registry timed out; this typically indicates network or SDN problems.

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 192.168.12.10 timed out.
              This could be temporary but could also indicate network or DNS problems.

       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 114.114.114.114 timed out.
              This could be temporary but could also indicate network or DNS problems.

       [Note] Summary of diagnostics execution (version v1.1.4):
       [Note] Warnings seen: 2
       [Note] Errors seen: 1

[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry

WARN:  [DClu1012 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:274]
       The pod logs for the "docker-registry-1-heesa" pod belonging to
       the "docker-registry" service indicated unknown errors.
       This could result in problems with builds or deployments.
       Please examine the log entries to determine if there might be
       any related problems:

       time="2016-04-06T07:24:41.541914354Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=412573cd-bfba-4aed-bfa0-5919f4e68e40 http.request.method=GET http.request.remoteaddr="10.1.0.1:43931" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe 
       time="2016-04-06T07:24:42.390638938Z" level=error msg="OpenShift client error: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/default/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=9fde30b2-d55d-4f78-9af8-f6b873090dc7 http.request.method=POST http.request.remoteaddr="10.1.0.1:43932" http.request.uri="/v2/default/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="default/docker-2048" 
       time="2016-04-06T07:24:42.390734965Z" level=error msg="error checking authorization: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/default/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=9fde30b2-d55d-4f78-9af8-f6b873090dc7 http.request.method=POST http.request.remoteaddr="10.1.0.1:43932" http.request.uri="/v2/default/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="default/docker-2048" 
       time="2016-04-06T07:24:42.390798448Z" level=error msg="error authorizing context: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/default/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=9fde30b2-d55d-4f78-9af8-f6b873090dc7 http.request.method=POST http.request.remoteaddr="10.1.0.1:43932" http.request.uri="/v2/default/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="default/docker-2048" 
       time="2016-04-06T07:27:49.813644382Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=59741cd8-09b2-4f05-a469-491583db0872 http.request.method=GET http.request.remoteaddr="10.1.1.1:60502" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe 
       time="2016-04-06T07:27:49.837934259Z" level=error msg="OpenShift client error: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=de02176d-1d1b-4adb-8aeb-72ce7d1228c1 http.request.method=POST http.request.remoteaddr="10.1.1.1:60503" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
       time="2016-04-06T07:27:49.838007015Z" level=error msg="error checking authorization: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=de02176d-1d1b-4adb-8aeb-72ce7d1228c1 http.request.method=POST http.request.remoteaddr="10.1.1.1:60503" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
       time="2016-04-06T07:27:49.838057676Z" level=error msg="error authorizing context: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=de02176d-1d1b-4adb-8aeb-72ce7d1228c1 http.request.method=POST http.request.remoteaddr="10.1.1.1:60503" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
       time="2016-04-06T07:46:05.53510725Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c62949-53f6-441c-9eba-5fdbfc93cbf7 http.request.method=GET http.request.remoteaddr="10.1.0.1:44213" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe 
       time="2016-04-06T07:46:05.557838291Z" level=error msg="OpenShift client error: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=06ba3188-19af-402e-a5cd-fa98274e9dc3 http.request.method=POST http.request.remoteaddr="10.1.0.1:44214" http.request.uri="/v2/liujie15/test/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/test" 
       time="2016-04-06T07:46:05.557906303Z" level=error msg="error checking authorization: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=06ba3188-19af-402e-a5cd-fa98274e9dc3 http.request.method=POST http.request.remoteaddr="10.1.0.1:44214" http.request.uri="/v2/liujie15/test/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/test" 
       time="2016-04-06T07:46:05.557957992Z" level=error msg="error authorizing context: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=06ba3188-19af-402e-a5cd-fa98274e9dc3 http.request.method=POST http.request.remoteaddr="10.1.0.1:44214" http.request.uri="/v2/liujie15/test/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/test" 
       time="2016-04-06T07:48:58.091960494Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=0f0b8eb7-1c49-4bd6-be08-367bd8652cff http.request.method=GET http.request.remoteaddr="10.1.1.1:36952" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe 
       time="2016-04-06T07:48:58.114913532Z" level=error msg="OpenShift client error: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
       time="2016-04-06T07:48:58.114998199Z" level=error msg="error checking authorization: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048" 
       time="2016-04-06T07:48:58.115072797Z" level=error msg="error authorizing context: Post https://openshift-container-deploy2:8443/oapi/v1/namespaces/liujie15/localsubjectaccessreviews: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.142.230:5000" http.request.id=76c247c1-7932-4ff1-b63f-1cdae37824b7 http.request.method=POST http.request.remoteaddr="10.1.1.1:36953" http.request.uri="/v2/liujie15/docker-2048/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=e2b22ffd-6700-4bd2-86d7-2ee7dffd3dbe vars.name="liujie15/docker-2048"

[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects

Info:  clusterrolebinding/cluster-admins has more subjects than expected.

       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.

Info:  clusterrolebinding/cluster-admins has extra subject {User  admin    }.

Info:  clusterrolebinding/cluster-readers has more subjects than expected.

       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.

Info:  clusterrolebinding/cluster-readers has extra subject {ServiceAccount management-infra management-admin    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions

[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router

[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)

ERROR: [DClu3002 from diagnostic MasterNode@openshift/origin/pkg/diagnostics/cluster/master_node.go:99]
       Client error while retrieving node records. Client retrieved records
       during discovery, so this is likely to be a transient error. Try running
       diagnostics again. If this message persists, there may be a permissions
       problem with getting node records. The error was:

       (*errors.StatusError) found '<', expected: !, identifier, or 'end of string'

[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master

[Note] Skipping diagnostic: AnalyzeLogs
       Description: Check for recent problems in systemd service logs
       Because: journalctl is not present/functional on this host

[Note] Running diagnostic: MasterConfigCheck
       Description: Check the master config file

Info:  Found a master config file: /etc/origin/master/master-config.yaml

WARN:  [DH0005 from diagnostic MasterConfigCheck@openshift/origin/pkg/diagnostics/host/check_master_config.go:58]
       Validation of master config file '/etc/origin/master/master-config.yaml' warned:
       assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
       assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console

[Note] Skipping diagnostic: UnitStatus
       Description: Check status for related systemd units
       Because: systemd is not present/functional on this host

[Note] Summary of diagnostics execution (version v1.1.4):
[Note] Warnings seen: 2
[Note] Errors seen: 2
```

**Comment by miminar** [comment]
Sorry for the delay. It seems to me like you reinstalled master or at least recreated master/node certs after you had deployed the docker registry. Re-deploying it should solve the issue.

**Comment by sbadakhc** [comment]
Hi,

I seeing this across all builds and I can confirm I had to recreate the certs in order to overcome an issue with Openshift not providing login tokens to users.  Redeploying does not resolve the issue.

Can you confirm at what point the certs a recreated during the installation.  I have no option right now but to recreate them.

Thanks,
Sal.

**Comment by coreydaley** [comment]
closing due to age and inactivity, please re-open or create a new issue if you are still having this issue with an up-to-date version of origin
