### ISSUE TITLE
TestTriggers_MultipleICTs 

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9856]
```
--- FAIL: TestTriggers_MultipleICTs (37.14s)
	deploy_trigger_test.go:468: Should not trigger a new deployment in response to the first imagestream update
	deploy_trigger_test.go:444: Waiting for image stream mapping to be reflected in the image stream status...
	deploy_trigger_test.go:457: Still waiting for latest tag status on imagestream "test-image-stream"
	deploy_trigger_test.go:454: imagestream "test-image-stream" now has status with tags: map[string]api.TagEventList{"latest":api.TagEventList{Items:[]api.TagEvent{api.TagEvent{Created:unversioned.Time{Time:time.Time{sec:63604111725, nsec:0, loc:(*time.Location)(0x72ac5e0)}}, DockerImageReference:"registry:8080/integration/test-image-stream@sha256:00000000000000000000000000000001", Image:"sha256:00000000000000000000000000000001", Generation:1}}, Conditions:[]api.TagEventCondition(nil)}}
	deploy_trigger_test.go:488: timed out waiting for the first image update to happen
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3362/console

**Comment by kargakis** [comment]
This happens only in https://github.com/openshift/origin/pull/9349. The test needs to set the namespace in image streams. I will keep this open until that PR is merged.

**Comment by kargakis** [comment]
Fixed in #9349

**Comment by miminar** [comment]
There's a new occurrence in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/4200/consoleFull#-70533943856bf4006e4b05b79524e5923

**Comment by danwinship** [comment]
@kargakis Still failing I think: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/5127/consoleFull#55701301556bf4006e4b05b79524e5923. That's from a post-10448 build, and it looks like it was waiting 2 minutes rather than 30 seconds in the logs, but it still ends up timing out

**Comment by kargakis** [comment]
Interesting, this waits for the second image update to happen
```
I0817 11:58:29.580930    2940 controller.go:133] Updated 1 deployment configs for trigger on image stream "integration/test-image-stream"
I0817 11:58:29.581550    2940 factory.go:118] Updating deployment config "config"
I0817 11:58:29.585089    2940 controller.go:358] Updated the status for "integration/config" (observed generation: 2)
I0817 11:58:29.585419    2940 factory.go:118] Updating deployment config "config"
I0817 11:58:29.586290    2940 controller.go:43] Detecting image changes for deployment config "integration/config"
I0817 11:58:29.586311    2940 controller.go:78] Couldn't find latest tag event for tag "latest" in image stream "integration/sample"
I0817 11:58:29.586322    2940 controller.go:133] Updated 0 deployment configs for trigger on image stream "integration/sample"
I0817 11:58:29.588939    2940 helper.go:740] UpdateTrackingTags: stream=integration/sample, updatedTag=latest, updatedImage.dockerImageReference=samplePullSpec, updatedImage.image=sampleImage
I0817 11:58:29.593704    2940 factory.go:123] Image stream "sample" updated.
I0817 11:58:29.596168    2940 image_change_controller.go:47] Build image change controller detected ImageStream change 
I0817 11:58:29.605763    2940 controller.go:43] Detecting image changes for deployment config "integration/config"
I0817 11:58:29.610811    2940 factory.go:118] Updating deployment config "config"
I0817 11:58:29.611453    2940 controller.go:133] Updated 1 deployment configs for trigger on image stream "integration/sample"
--- FAIL: TestTriggers_MultipleICTs (128.97s)
	deploy_trigger_test.go:453: Should not trigger a new deployment in response to the first imagestream update
	deploy_trigger_test.go:427: Waiting for image stream mapping to be reflected in the image stream status...
	deploy_trigger_test.go:440: Still waiting for latest tag status on imagestream "test-image-stream"
	deploy_trigger_test.go:437: imagestream "test-image-stream" now has status with tags: map[string]api.TagEventList{"latest":api.TagEventList{Items:[]api.TagEvent{api.TagEvent{Created:unversioned.Time{Time:time.Time{sec:63607046189, nsec:0, loc:(*time.Location)(0x771fae0)}}, DockerImageReference:"registry:8080/integration/test-image-stream@sha256:00000000000000000000000000000001", Image:"sha256:00000000000000000000000000000001", Generation:1}}, Conditions:[]api.TagEventCondition(nil)}}
	deploy_trigger_test.go:477: Should trigger a new deployment in response to the second imagestream update
	deploy_trigger_test.go:427: Waiting for image stream mapping to be reflected in the image stream status...
	deploy_trigger_test.go:437: imagestream "sample" now has status with tags: map[string]api.TagEventList{"latest":api.TagEventList{Items:[]api.TagEvent{api.TagEvent{Created:unversioned.Time{Time:time.Time{sec:63607046309, nsec:0, loc:(*time.Location)(0x771fae0)}}, DockerImageReference:"samplePullSpec", Image:"sampleImage", Generation:1}}, Conditions:[]api.TagEventCondition(nil)}}
	deploy_trigger_test.go:506: timed out waiting for the second image update to happen
FAIL
```
Anyway, this shouldn't be a problem with https://github.com/openshift/origin/pull/10456 (note also that we reverted the times back to 30s). In any case, if this happens again, please reopen.
